// Code generated by protoc-gen-go. DO NOT EDIT.
// source: object.proto

package append

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DataType int32

const (
	DataType_DataTypeUnknown DataType = 0
	DataType_Create          DataType = 1
	DataType_Amend           DataType = 2
)

var DataType_name = map[int32]string{
	0: "DataTypeUnknown",
	1: "Create",
	2: "Amend",
}
var DataType_value = map[string]int32{
	"DataTypeUnknown": 0,
	"Create":          1,
	"Amend":           2,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}
func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_object_faccdc74ad4274f7, []int{0}
}

// An object represents a user provided key value pair. Keys are required to be globally unique within a DB.
type Object struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                *any.Any `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,3,opt,name=Meta,proto3" json:"Meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_object_faccdc74ad4274f7, []int{0}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (dst *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(dst, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Object) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Object) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

// State represents the integritiy check at object level.
type State struct {
	ObjHash              uint64   `protobuf:"varint,1,opt,name=ObjHash,proto3" json:"ObjHash,omitempty"`
	ChainHash            uint64   `protobuf:"varint,2,opt,name=ChainHash,proto3" json:"ChainHash,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_object_faccdc74ad4274f7, []int{1}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetObjHash() uint64 {
	if m != nil {
		return m.ObjHash
	}
	return 0
}

func (m *State) GetChainHash() uint64 {
	if m != nil {
		return m.ChainHash
	}
	return 0
}

func (m *State) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Meta allows for user set annotations, which may be used in indexing as well. Timestamp is set by the DB
type Meta struct {
	Type                 DataType             `protobuf:"varint,1,opt,name=Type,proto3,enum=append.DataType" json:"Type,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Fields               *any.Any             `protobuf:"bytes,3,opt,name=Fields,proto3" json:"Fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_object_faccdc74ad4274f7, []int{2}
}
func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (dst *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(dst, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetType() DataType {
	if m != nil {
		return m.Type
	}
	return DataType_DataTypeUnknown
}

func (m *Meta) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Meta) GetFields() *any.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

// Chunk represents a full entry in the DB
type Chunk struct {
	State                *State   `protobuf:"bytes,1,opt,name=State,proto3" json:"State,omitempty"`
	Obj                  *Object  `protobuf:"bytes,2,opt,name=Obj,proto3" json:"Obj,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_object_faccdc74ad4274f7, []int{3}
}
func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (dst *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(dst, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Chunk) GetObj() *Object {
	if m != nil {
		return m.Obj
	}
	return nil
}

// Test is used in some unit tests to generate an any.Any.
type Test struct {
	Value                string   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_object_faccdc74ad4274f7, []int{4}
}
func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (dst *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(dst, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Object)(nil), "append.Object")
	proto.RegisterType((*State)(nil), "append.State")
	proto.RegisterType((*Meta)(nil), "append.Meta")
	proto.RegisterType((*Chunk)(nil), "append.Chunk")
	proto.RegisterType((*Test)(nil), "append.Test")
	proto.RegisterEnum("append.DataType", DataType_name, DataType_value)
}

func init() { proto.RegisterFile("object.proto", fileDescriptor_object_faccdc74ad4274f7) }

var fileDescriptor_object_faccdc74ad4274f7 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6b, 0xe3, 0x30,
	0x14, 0x5c, 0x27, 0xb6, 0x37, 0x7e, 0xc9, 0x66, 0x8d, 0x36, 0x07, 0x6f, 0x08, 0xac, 0xf1, 0xee,
	0x21, 0x84, 0xc5, 0x81, 0x14, 0x4a, 0xaf, 0x69, 0x4a, 0x29, 0x94, 0x36, 0xa0, 0xa4, 0x3d, 0x14,
	0x7a, 0x90, 0x9b, 0xd7, 0xd8, 0xf9, 0x90, 0x4d, 0x2c, 0x53, 0xfc, 0x3f, 0xfa, 0x83, 0x8b, 0x25,
	0xab, 0x81, 0xb6, 0x37, 0x69, 0x66, 0x18, 0xcd, 0xbc, 0x27, 0xe8, 0xa4, 0xd1, 0x06, 0x9f, 0x44,
	0x98, 0x1d, 0x52, 0x91, 0x12, 0x9b, 0x65, 0x19, 0xf2, 0x55, 0xff, 0xf7, 0x3a, 0x4d, 0xd7, 0x3b,
	0x1c, 0x4b, 0x34, 0x2a, 0x9e, 0xc7, 0x8c, 0x97, 0x4a, 0xd2, 0xff, 0xf3, 0x91, 0x12, 0xc9, 0x1e,
	0x73, 0xc1, 0xf6, 0x99, 0x12, 0x04, 0x31, 0xd8, 0x73, 0xe9, 0x49, 0x5c, 0x68, 0x5e, 0x63, 0xe9,
	0x19, 0xbe, 0x31, 0x74, 0x68, 0x75, 0x24, 0x23, 0xb0, 0xee, 0xd9, 0xae, 0x40, 0xaf, 0xe1, 0x1b,
	0xc3, 0xf6, 0xa4, 0x17, 0x2a, 0xb3, 0x50, 0x9b, 0x85, 0x53, 0x5e, 0x52, 0x25, 0x21, 0x3e, 0x98,
	0x37, 0x28, 0x98, 0xd7, 0x94, 0xd2, 0x4e, 0xa8, 0xa2, 0x85, 0x15, 0x46, 0x25, 0x13, 0x3c, 0x82,
	0xb5, 0x10, 0x4c, 0x20, 0xf1, 0xe0, 0xfb, 0x3c, 0xda, 0x5c, 0xb1, 0x3c, 0x96, 0x8f, 0x99, 0x54,
	0x5f, 0xc9, 0x00, 0x9c, 0x59, 0xcc, 0x12, 0x2e, 0xb9, 0x86, 0xe4, 0x8e, 0x40, 0xc5, 0x2e, 0x92,
	0x35, 0x67, 0xa2, 0x38, 0xa0, 0x7c, 0xa7, 0x43, 0x8f, 0x40, 0xf0, 0x6a, 0xa8, 0x04, 0xe4, 0x1f,
	0x98, 0xcb, 0x32, 0x43, 0xe9, 0xdd, 0x9d, 0xb8, 0x3a, 0xc9, 0x05, 0x13, 0xac, 0xc2, 0xa9, 0x64,
	0xc9, 0x19, 0x38, 0x4b, 0x3d, 0x8a, 0xba, 0x5f, 0xff, 0x53, 0xbf, 0x77, 0x05, 0x3d, 0x8a, 0xc9,
	0x7f, 0xb0, 0x2f, 0x13, 0xdc, 0xad, 0xf2, 0xba, 0xeb, 0xd7, 0x63, 0xa9, 0x35, 0xc1, 0x2d, 0x58,
	0xb3, 0xb8, 0xe0, 0x5b, 0xf2, 0xb7, 0xae, 0x2f, 0x73, 0xb5, 0x27, 0x3f, 0x74, 0x2e, 0x09, 0xd2,
	0x7a, 0x34, 0x3e, 0x34, 0xe7, 0xd1, 0xa6, 0xce, 0xd3, 0xd5, 0x12, 0xb5, 0x20, 0x5a, 0x51, 0xc1,
	0x00, 0xcc, 0x25, 0xe6, 0x82, 0xf4, 0xf4, 0x6e, 0xd4, 0xbe, 0xd4, 0x65, 0x74, 0x0a, 0x2d, 0xdd,
	0x93, 0xfc, 0x82, 0x9f, 0xfa, 0x7c, 0xc7, 0xb7, 0x3c, 0x7d, 0xe1, 0xee, 0x37, 0x02, 0x60, 0xcf,
	0x0e, 0xc8, 0x04, 0xba, 0x06, 0x71, 0xc0, 0x9a, 0xee, 0x91, 0xaf, 0xdc, 0xc6, 0x79, 0xeb, 0xa1,
	0xfe, 0x4b, 0x91, 0x2d, 0x5b, 0x9c, 0xbc, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xca, 0xf8, 0xd9,
	0x6a, 0x02, 0x00, 0x00,
}
