version: 2

jobs:
  test:
    docker:
    - image: carapaceio/go:1.11

    steps:
    - checkout

    - checkout

    - restore_cache:
        keys:
        - go-mod-v1-{{ checksum "go.sum" }}

    - run:
        name: Get dependencies
        command: |
          ./configure

    - save_cache:
        key: go-mod-v1-{{ checksum "go.sum" }}
        paths:
        - "/go/pkg/mod"

    - run:
        name: Test and run linters.
        command: |
          go test ./... -v -race -coverprofile=coverage.out
          goveralls -coverprofile=coverage.out -service=cirlceci -repotoken $COVERALLS_REPO_TOKEN

workflows:
  version: 2
  tests:
    jobs: [test]