// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/carapace/core/pkg/v0 (interfaces: Authenticator)

// Package mock is a generated GoMock package.
package mock

import (
	proto "github.com/carapace/core/api/v0/proto"
	gomock "github.com/golang/mock/gomock"
	proto0 "github.com/golang/protobuf/proto"
	reflect "reflect"
)

// MockAuthenticator is a mock of Authenticator interface
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// CheckSignatures mocks base method
func (m *MockAuthenticator) CheckSignatures(arg0 proto0.Message, arg1 *proto.Witness) (bool, string, error) {
	ret := m.ctrl.Call(m, "CheckSignatures", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckSignatures indicates an expected call of CheckSignatures
func (mr *MockAuthenticatorMockRecorder) CheckSignatures(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSignatures", reflect.TypeOf((*MockAuthenticator)(nil).CheckSignatures), arg0, arg1)
}
