// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	ApiVersion           string   `protobuf:"bytes,1,opt,name=ApiVersion,proto3" json:"ApiVersion,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Meta                 *any.Any `protobuf:"bytes,4,opt,name=Meta,proto3" json:"Meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_d8cd27249e376ef7, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *Header) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Header) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Header) GetMeta() *any.Any {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Witness struct {
	Signatures           map[string][]byte `protobuf:"bytes,1,rep,name=Signatures,proto3" json:"Signatures,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Witness) Reset()         { *m = Witness{} }
func (m *Witness) String() string { return proto.CompactTextString(m) }
func (*Witness) ProtoMessage()    {}
func (*Witness) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_d8cd27249e376ef7, []int{1}
}
func (m *Witness) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Witness.Unmarshal(m, b)
}
func (m *Witness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Witness.Marshal(b, m, deterministic)
}
func (dst *Witness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Witness.Merge(dst, src)
}
func (m *Witness) XXX_Size() int {
	return xxx_messageInfo_Witness.Size(m)
}
func (m *Witness) XXX_DiscardUnknown() {
	xxx_messageInfo_Witness.DiscardUnknown(m)
}

var xxx_messageInfo_Witness proto.InternalMessageInfo

func (m *Witness) GetSignatures() map[string][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type State struct {
	State                float64              `protobuf:"fixed64,1,opt,name=State,proto3" json:"State,omitempty"`
	PrevState            float64              `protobuf:"fixed64,2,opt,name=PrevState,proto3" json:"PrevState,omitempty"`
	TimeAccepted         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=TimeAccepted,proto3" json:"TimeAccepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_d8cd27249e376ef7, []int{2}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetState() float64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *State) GetPrevState() float64 {
	if m != nil {
		return m.PrevState
	}
	return 0
}

func (m *State) GetTimeAccepted() *timestamp.Timestamp {
	if m != nil {
		return m.TimeAccepted
	}
	return nil
}

type Config struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Witness              *Witness `protobuf:"bytes,2,opt,name=Witness,proto3" json:"Witness,omitempty"`
	State                *State   `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"`
	Spec                 *any.Any `protobuf:"bytes,4,opt,name=Spec,proto3" json:"Spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_d8cd27249e376ef7, []int{3}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Config) GetWitness() *Witness {
	if m != nil {
		return m.Witness
	}
	return nil
}

func (m *Config) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Config) GetSpec() *any.Any {
	if m != nil {
		return m.Spec
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "v1.config.Header")
	proto.RegisterType((*Witness)(nil), "v1.config.Witness")
	proto.RegisterMapType((map[string][]byte)(nil), "v1.config.Witness.SignaturesEntry")
	proto.RegisterType((*State)(nil), "v1.config.State")
	proto.RegisterType((*Config)(nil), "v1.config.Config")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_config_d8cd27249e376ef7) }

var fileDescriptor_config_d8cd27249e376ef7 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x51, 0xeb, 0xd3, 0x30,
	0x14, 0xc5, 0x49, 0xd7, 0xff, 0x64, 0xb7, 0x03, 0x67, 0xd8, 0x43, 0x2d, 0xa2, 0xa3, 0x0f, 0x52,
	0x41, 0x32, 0x56, 0x5f, 0x44, 0x50, 0xd8, 0x44, 0x10, 0x44, 0x91, 0x6c, 0x28, 0xf8, 0x96, 0x75,
	0x77, 0x25, 0xb8, 0xa6, 0xa5, 0xcd, 0x0a, 0xd5, 0xaf, 0xe0, 0xb7, 0xf1, 0x0b, 0x4a, 0x93, 0x75,
	0xab, 0x1b, 0xfc, 0xdf, 0x6e, 0xcf, 0xf9, 0x85, 0xde, 0x73, 0x2e, 0x8c, 0x93, 0x5c, 0xed, 0x65,
	0xca, 0x8a, 0x32, 0xd7, 0x39, 0x1d, 0xd5, 0x0b, 0x66, 0x85, 0xe0, 0x71, 0x9a, 0xe7, 0xe9, 0x01,
	0xe7, 0xc6, 0xd8, 0x1e, 0xf7, 0x73, 0xa1, 0x1a, 0x4b, 0x05, 0xcf, 0xae, 0x2d, 0x2d, 0x33, 0xac,
	0xb4, 0xc8, 0x0a, 0x0b, 0x84, 0xbf, 0x60, 0xf8, 0x11, 0xc5, 0x0e, 0x4b, 0xfa, 0x14, 0x60, 0x59,
	0xc8, 0x6f, 0x58, 0x56, 0x32, 0x57, 0x3e, 0x99, 0x91, 0x68, 0xc4, 0x7b, 0x0a, 0xa5, 0xe0, 0x7e,
	0x92, 0x6a, 0xe7, 0x3b, 0xc6, 0x31, 0x73, 0xab, 0x7d, 0x11, 0x19, 0xfa, 0x03, 0xab, 0xb5, 0x33,
	0x8d, 0xc0, 0xfd, 0x8c, 0x5a, 0xf8, 0xee, 0x8c, 0x44, 0x5e, 0x3c, 0x65, 0x76, 0x03, 0xd6, 0x6d,
	0xc0, 0x96, 0xaa, 0xe1, 0x86, 0x08, 0xff, 0x10, 0x78, 0xf0, 0x5d, 0x6a, 0x85, 0x55, 0x45, 0x57,
	0x00, 0x6b, 0x99, 0x2a, 0xa1, 0x8f, 0x25, 0x56, 0x3e, 0x99, 0x0d, 0x22, 0x2f, 0x0e, 0xd9, 0x39,
	0x23, 0x3b, 0x71, 0xec, 0x02, 0x7d, 0x50, 0xba, 0x6c, 0x78, 0xef, 0x55, 0xf0, 0x16, 0x1e, 0x5e,
	0xd9, 0x74, 0x02, 0x83, 0x9f, 0xd8, 0x9c, 0xd2, 0xb4, 0x23, 0x9d, 0xc2, 0x5d, 0x2d, 0x0e, 0x47,
	0x34, 0x39, 0xc6, 0xdc, 0x7e, 0xbc, 0x71, 0x5e, 0x93, 0xf0, 0x37, 0xdc, 0xad, 0xb5, 0xd0, 0xd8,
	0x22, 0x66, 0x30, 0xcf, 0x08, 0x3f, 0xa9, 0x4f, 0x60, 0xf4, 0xb5, 0xc4, 0xda, 0x3a, 0x8e, 0x71,
	0x2e, 0x02, 0x7d, 0x07, 0xe3, 0x8d, 0xcc, 0x70, 0x99, 0x24, 0x58, 0x68, 0xdc, 0x99, 0x46, 0xbc,
	0x38, 0xb8, 0x49, 0xbf, 0xe9, 0xfa, 0xe7, 0xff, 0xf1, 0xe1, 0x5f, 0x02, 0xc3, 0xf7, 0x26, 0x2a,
	0x7d, 0xd1, 0x9d, 0xc4, 0xfc, 0xdf, 0x8b, 0x1f, 0xf5, 0x6a, 0xb0, 0x06, 0xef, 0x6e, 0xf6, 0xf2,
	0x5c, 0xa0, 0xd9, 0xc8, 0x8b, 0xe9, 0x6d, 0x65, 0xfc, 0xdc, 0xf1, 0xf3, 0x2e, 0x97, 0x5d, 0x6e,
	0xd2, 0x63, 0x8d, 0xde, 0x25, 0x8d, 0xc0, 0x5d, 0x17, 0x98, 0xdc, 0x7f, 0xc1, 0x96, 0x58, 0xb9,
	0x3f, 0x9c, 0x7a, 0xb1, 0x1d, 0x1a, 0xe7, 0xd5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xbd,
	0xe6, 0xeb, 0xa1, 0x02, 0x00, 0x00,
}
