// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keys.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Secret struct {
	Namescace            *Namespace `protobuf:"bytes,1,opt,name=Namescace,proto3" json:"Namescace,omitempty"`
	Asset                Asset      `protobuf:"varint,2,opt,name=Asset,proto3,enum=v1.assets.Asset" json:"Asset,omitempty"`
	Secrets              [][]byte   `protobuf:"bytes,3,rep,name=Secrets,proto3" json:"Secrets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Secret) Reset()         { *m = Secret{} }
func (m *Secret) String() string { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()    {}
func (*Secret) Descriptor() ([]byte, []int) {
	return fileDescriptor_keys_5f87c48b287f4902, []int{0}
}
func (m *Secret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Secret.Unmarshal(m, b)
}
func (m *Secret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Secret.Marshal(b, m, deterministic)
}
func (dst *Secret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Secret.Merge(dst, src)
}
func (m *Secret) XXX_Size() int {
	return xxx_messageInfo_Secret.Size(m)
}
func (m *Secret) XXX_DiscardUnknown() {
	xxx_messageInfo_Secret.DiscardUnknown(m)
}

var xxx_messageInfo_Secret proto.InternalMessageInfo

func (m *Secret) GetNamescace() *Namespace {
	if m != nil {
		return m.Namescace
	}
	return nil
}

func (m *Secret) GetAsset() Asset {
	if m != nil {
		return m.Asset
	}
	return Asset_AssetUnknown
}

func (m *Secret) GetSecrets() [][]byte {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func init() {
	proto.RegisterType((*Secret)(nil), "v1.keys.Secret")
}

func init() { proto.RegisterFile("keys.proto", fileDescriptor_keys_5f87c48b287f4902) }

var fileDescriptor_keys_5f87c48b287f4902 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4e, 0xad, 0x2c,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x33, 0xd4, 0x03, 0x71, 0xa5, 0xf8, 0xf3,
	0x12, 0x73, 0x53, 0x8b, 0x0b, 0x12, 0x93, 0x53, 0x21, 0x32, 0x52, 0x3c, 0x89, 0xc5, 0xc5, 0xa9,
	0x25, 0x50, 0x75, 0x4a, 0x8d, 0x8c, 0x5c, 0x6c, 0xc1, 0xa9, 0xc9, 0x45, 0xa9, 0x25, 0x42, 0xa6,
	0x5c, 0x9c, 0x7e, 0x20, 0xb5, 0xc9, 0x89, 0xc9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46,
	0xe2, 0x7a, 0x65, 0x86, 0x7a, 0x08, 0x03, 0xfc, 0x60, 0xac, 0x20, 0x84, 0x4a, 0x21, 0x35, 0x2e,
	0x56, 0x47, 0x90, 0x89, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0x02, 0x20, 0x2d, 0x50, 0x2b,
	0xc0, 0xe2, 0x41, 0x10, 0x69, 0x21, 0x09, 0x2e, 0x76, 0x88, 0x45, 0xc5, 0x12, 0xcc, 0x0a, 0xcc,
	0x1a, 0x3c, 0x41, 0x30, 0xae, 0x13, 0x4b, 0x14, 0x53, 0x99, 0x61, 0x12, 0x1b, 0xd8, 0x41, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xe1, 0x75, 0x7e, 0xc6, 0x00, 0x00, 0x00,
}
