// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocols.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Protocol int32

const (
	Protocol_ProtocolsUnknown Protocol = 0
	Protocol_Transfer         Protocol = 1
	Protocol_Vote             Protocol = 2
)

var Protocol_name = map[int32]string{
	0: "ProtocolsUnknown",
	1: "Transfer",
	2: "Vote",
}
var Protocol_value = map[string]int32{
	"ProtocolsUnknown": 0,
	"Transfer":         1,
	"Vote":             2,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_protocols_334be3b5d2af742a, []int{0}
}

func init() {
	proto.RegisterEnum("v1.protocols.Protocol", Protocol_name, Protocol_value)
}

func init() { proto.RegisterFile("protocols.proto", fileDescriptor_protocols_334be3b5d2af742a) }

var fileDescriptor_protocols_334be3b5d2af742a = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0x29, 0xd6, 0x03, 0xb3, 0x84, 0x78, 0xca, 0x0c, 0xf5, 0xe0, 0x62, 0x5a,
	0x16, 0x5c, 0x1c, 0x01, 0x50, 0x8e, 0x90, 0x08, 0x97, 0x00, 0x8c, 0x5d, 0x1c, 0x9a, 0x97, 0x9d,
	0x97, 0x5f, 0x9e, 0x27, 0xc0, 0x20, 0xc4, 0xc3, 0xc5, 0x11, 0x52, 0x94, 0x98, 0x57, 0x9c, 0x96,
	0x5a, 0x24, 0xc0, 0x28, 0xc4, 0xc1, 0xc5, 0x12, 0x96, 0x5f, 0x92, 0x2a, 0xc0, 0xe4, 0xc4, 0x12,
	0xc5, 0x54, 0x66, 0x98, 0xc4, 0x06, 0x36, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x69,
	0x88, 0x5f, 0x67, 0x00, 0x00, 0x00,
}
