// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionType int32

const (
	TransactionType_TransactionTypeUnknown TransactionType = 0
	TransactionType_Transfer               TransactionType = 1
	TransactionType_SCCreation             TransactionType = 2
	TransactionType_SCInvocation           TransactionType = 3
	TransactionType_Vote                   TransactionType = 4
)

var TransactionType_name = map[int32]string{
	0: "TransactionTypeUnknown",
	1: "Transfer",
	2: "SCCreation",
	3: "SCInvocation",
	4: "Vote",
}
var TransactionType_value = map[string]int32{
	"TransactionTypeUnknown": 0,
	"Transfer":               1,
	"SCCreation":             2,
	"SCInvocation":           3,
	"Vote":                   4,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_c9ff08974c612556, []int{0}
}

type Transaction struct {
	Type                 TransactionType `protobuf:"varint,1,opt,name=Type,proto3,enum=v1.transaction.TransactionType" json:"Type,omitempty"`
	Recipient            string          `protobuf:"bytes,2,opt,name=Recipient,proto3" json:"Recipient,omitempty"`
	Amount               float64         `protobuf:"fixed64,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Fee                  float64         `protobuf:"fixed64,4,opt,name=Fee,proto3" json:"Fee,omitempty"`
	Meta                 []byte          `protobuf:"bytes,5,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Signatures           *Signatures     `protobuf:"bytes,6,opt,name=Signatures,proto3" json:"Signatures,omitempty"`
	Namespace            *Namespace      `protobuf:"bytes,7,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_c9ff08974c612556, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_TransactionTypeUnknown
}

func (m *Transaction) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *Transaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetFee() float64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Transaction) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Transaction) GetSignatures() *Signatures {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *Transaction) GetNamespace() *Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type TransactionResponse struct {
	Payload              []byte     `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Response             *Response  `protobuf:"bytes,2,opt,name=Response,proto3" json:"Response,omitempty"`
	Namespace            *Namespace `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_c9ff08974c612556, []int{1}
}
func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResponse.Unmarshal(m, b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
}
func (dst *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(dst, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResponse.Size(m)
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func (m *TransactionResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *TransactionResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *TransactionResponse) GetNamespace() *Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "v1.transaction.Transaction")
	proto.RegisterType((*TransactionResponse)(nil), "v1.transaction.TransactionResponse")
	proto.RegisterEnum("v1.transaction.TransactionType", TransactionType_name, TransactionType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionServiceClient interface {
	Create(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionResponse, error)
}

type transactionServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransactionServiceClient(cc *grpc.ClientConn) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) Create(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, "/v1.transaction.TransactionService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
type TransactionServiceServer interface {
	Create(context.Context, *Transaction) (*TransactionResponse, error)
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

func _TransactionService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.transaction.TransactionService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).Create(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.transaction.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TransactionService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_transaction_c9ff08974c612556) }

var fileDescriptor_transaction_c9ff08974c612556 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xd1, 0x6a, 0xd4, 0x40,
	0x14, 0x75, 0x92, 0x98, 0xee, 0xde, 0x0d, 0x69, 0xbc, 0x62, 0x1d, 0xa2, 0x60, 0xa8, 0x2f, 0xc1,
	0x87, 0xc0, 0xa6, 0xf8, 0x01, 0x75, 0x41, 0xa8, 0x50, 0x91, 0x49, 0xf5, 0xc1, 0x27, 0xc7, 0xf4,
	0x5a, 0x82, 0x76, 0x26, 0x24, 0xd3, 0xc8, 0x7e, 0x82, 0x9f, 0xe0, 0xdf, 0x4a, 0xa6, 0xc9, 0x26,
	0xdd, 0x87, 0xc5, 0xb7, 0xb9, 0xe7, 0x9c, 0x7b, 0xe7, 0x9e, 0xc3, 0x85, 0x27, 0xa6, 0x91, 0xaa,
	0x95, 0xa5, 0xa9, 0xb4, 0xca, 0xea, 0x46, 0x1b, 0x8d, 0x61, 0xb7, 0xce, 0x66, 0x68, 0x1c, 0x56,
	0xd7, 0xa4, 0x4c, 0x65, 0xb6, 0xf7, 0x7c, 0x1c, 0x36, 0xd4, 0xd6, 0x5a, 0xb5, 0x34, 0xd4, 0xc7,
	0x4a, 0xde, 0x52, 0x5b, 0xcb, 0x72, 0x00, 0x4e, 0xff, 0x38, 0xb0, 0xba, 0x9a, 0x06, 0xe0, 0x19,
	0x78, 0x57, 0xdb, 0x9a, 0x38, 0x4b, 0x58, 0x1a, 0xe6, 0xaf, 0xb2, 0x87, 0xf3, 0xb3, 0x99, 0xb4,
	0x97, 0x09, 0x2b, 0xc6, 0x97, 0xb0, 0x14, 0x54, 0x56, 0x75, 0x45, 0xca, 0x70, 0x27, 0x61, 0xe9,
	0x52, 0x4c, 0x00, 0x9e, 0x80, 0x7f, 0x7e, 0xab, 0xef, 0x94, 0xe1, 0x6e, 0xc2, 0x52, 0x26, 0x86,
	0x0a, 0x23, 0x70, 0xdf, 0x13, 0x71, 0xcf, 0x82, 0xfd, 0x13, 0x11, 0xbc, 0x4b, 0x32, 0x92, 0x3f,
	0x4e, 0x58, 0x1a, 0x08, 0xfb, 0xc6, 0x1c, 0xa0, 0xa8, 0x6e, 0x94, 0x34, 0x77, 0x0d, 0xb5, 0xdc,
	0x4f, 0x58, 0xba, 0xca, 0xb1, 0x5f, 0xeb, 0xe2, 0xfc, 0x32, 0x9b, 0x18, 0x31, 0x53, 0xe1, 0x5b,
	0x58, 0x7e, 0x1c, 0x7d, 0xf2, 0x23, 0xdb, 0xf2, 0xbc, 0x6f, 0x99, 0xcc, 0xef, 0x68, 0x31, 0x29,
	0x4f, 0xff, 0x32, 0x78, 0x3a, 0x33, 0x28, 0x86, 0xe8, 0x90, 0xc3, 0xd1, 0x27, 0xb9, 0xfd, 0xa5,
	0xe5, 0xb5, 0x8d, 0x25, 0x10, 0x63, 0x89, 0x6b, 0x58, 0x8c, 0x2a, 0xeb, 0x7b, 0x95, 0x3f, 0xeb,
	0xff, 0xd9, 0x85, 0x3e, 0x92, 0x62, 0x27, 0x7b, 0xb8, 0x9b, 0xfb, 0xbf, 0xbb, 0xbd, 0xb9, 0x81,
	0xe3, 0xbd, 0xec, 0x31, 0x86, 0x93, 0x3d, 0xe8, 0xb3, 0xfa, 0xa9, 0xf4, 0x6f, 0x15, 0x3d, 0xc2,
	0x00, 0x16, 0x96, 0xfb, 0x41, 0x4d, 0xc4, 0x30, 0x04, 0x28, 0x36, 0x9b, 0x86, 0x64, 0x2f, 0x8c,
	0x1c, 0x8c, 0x20, 0x28, 0x36, 0x17, 0xaa, 0xd3, 0xe5, 0x3d, 0xe2, 0xe2, 0x02, 0xbc, 0x2f, 0xda,
	0x50, 0xe4, 0xe5, 0xdf, 0x00, 0x67, 0x53, 0x0b, 0x6a, 0xba, 0xaa, 0x24, 0xfc, 0x00, 0xbe, 0xed,
	0x27, 0x7c, 0x71, 0xe0, 0x24, 0xe2, 0xd7, 0x07, 0xc8, 0x31, 0x81, 0x77, 0xde, 0x57, 0xa7, 0x5b,
	0x7f, 0xf7, 0xed, 0xfd, 0x9d, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xcc, 0x06, 0x4b, 0xd5,
	0x02, 0x00, 0x00,
}
