// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WalletGen struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletGen) Reset()         { *m = WalletGen{} }
func (m *WalletGen) String() string { return proto.CompactTextString(m) }
func (*WalletGen) ProtoMessage()    {}
func (*WalletGen) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_ede7c4d30853bc1b, []int{0}
}
func (m *WalletGen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletGen.Unmarshal(m, b)
}
func (m *WalletGen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletGen.Marshal(b, m, deterministic)
}
func (dst *WalletGen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletGen.Merge(dst, src)
}
func (m *WalletGen) XXX_Size() int {
	return xxx_messageInfo_WalletGen.Size(m)
}
func (m *WalletGen) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletGen.DiscardUnknown(m)
}

var xxx_messageInfo_WalletGen proto.InternalMessageInfo

func (m *WalletGen) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*WalletGen)(nil), "v1.config.walletGen")
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor_wallet_ede7c4d30853bc1b) }

var fileDescriptor_wallet_ede7c4d30853bc1b = []byte{
	// 86 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4f, 0xcc, 0xc9,
	0x49, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2c, 0x33, 0xd4, 0x4b, 0xce, 0xcf,
	0x4b, 0xcb, 0x4c, 0x57, 0x92, 0xe7, 0xe2, 0x84, 0x48, 0xb9, 0xa7, 0xe6, 0x09, 0x09, 0x71, 0xb1,
	0xf8, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4e, 0x2c, 0x51,
	0x4c, 0x65, 0x86, 0x49, 0x6c, 0x60, 0x8d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xd2,
	0x7b, 0xf5, 0x48, 0x00, 0x00, 0x00,
}
