// Code generated by protoc-gen-go. DO NOT EDIT.
// source: assets.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Asset int32

const (
	Asset_AssetUnknown Asset = 0
	Asset_BTC          Asset = 1
)

var Asset_name = map[int32]string{
	0: "AssetUnknown",
	1: "BTC",
}
var Asset_value = map[string]int32{
	"AssetUnknown": 0,
	"BTC":          1,
}

func (x Asset) String() string {
	return proto.EnumName(Asset_name, int32(x))
}
func (Asset) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_assets_e5ac2fb6e8d0f6b6, []int{0}
}

func init() {
	proto.RegisterEnum("v0.Asset", Asset_name, Asset_value)
}

func init() { proto.RegisterFile("assets.proto", fileDescriptor_assets_e5ac2fb6e8d0f6b6) }

var fileDescriptor_assets_e5ac2fb6e8d0f6b6 = []byte{
	// 84 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2c, 0x2e, 0x4e,
	0x2d, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0xd0, 0x52, 0xe2, 0x62,
	0x75, 0x04, 0x89, 0x09, 0x09, 0x70, 0xf1, 0x80, 0x19, 0xa1, 0x79, 0xd9, 0x79, 0xf9, 0xe5, 0x79,
	0x02, 0x0c, 0x42, 0xec, 0x5c, 0xcc, 0x4e, 0x21, 0xce, 0x02, 0x8c, 0x4e, 0x2c, 0x51, 0x4c, 0x65,
	0x06, 0x49, 0x6c, 0x60, 0x4d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0xc4, 0xcc, 0x14,
	0x44, 0x00, 0x00, 0x00,
}
