// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conditions.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthLevelGreaterArg struct {
	Level                int32    `protobuf:"varint,1,opt,name=Level,proto3" json:"Level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthLevelGreaterArg) Reset()         { *m = AuthLevelGreaterArg{} }
func (m *AuthLevelGreaterArg) String() string { return proto.CompactTextString(m) }
func (*AuthLevelGreaterArg) ProtoMessage()    {}
func (*AuthLevelGreaterArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_conditions_865f38e94ddfcafd, []int{0}
}
func (m *AuthLevelGreaterArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLevelGreaterArg.Unmarshal(m, b)
}
func (m *AuthLevelGreaterArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLevelGreaterArg.Marshal(b, m, deterministic)
}
func (dst *AuthLevelGreaterArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLevelGreaterArg.Merge(dst, src)
}
func (m *AuthLevelGreaterArg) XXX_Size() int {
	return xxx_messageInfo_AuthLevelGreaterArg.Size(m)
}
func (m *AuthLevelGreaterArg) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLevelGreaterArg.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLevelGreaterArg proto.InternalMessageInfo

func (m *AuthLevelGreaterArg) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthLevelGreaterArg)(nil), "v0.AuthLevelGreaterArg")
}

func init() { proto.RegisterFile("conditions.proto", fileDescriptor_conditions_865f38e94ddfcafd) }

var fileDescriptor_conditions_865f38e94ddfcafd = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0xcf, 0x4b,
	0xc9, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33,
	0x50, 0xd2, 0xe6, 0x12, 0x76, 0x2c, 0x2d, 0xc9, 0xf0, 0x49, 0x2d, 0x4b, 0xcd, 0x71, 0x2f, 0x4a,
	0x4d, 0x2c, 0x49, 0x2d, 0x72, 0x2c, 0x4a, 0x17, 0x12, 0xe1, 0x62, 0x05, 0x0b, 0x49, 0x30, 0x2a,
	0x30, 0x6a, 0xb0, 0x06, 0x41, 0x38, 0x4e, 0x2c, 0x51, 0x4c, 0x65, 0x06, 0x49, 0x6c, 0x60, 0xdd,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x32, 0x20, 0xca, 0x86, 0x51, 0x00, 0x00, 0x00,
}
