// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	ApiVersion           string   `protobuf:"bytes,1,opt,name=ApiVersion,proto3" json:"ApiVersion,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Meta                 *any.Any `protobuf:"bytes,4,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Valid                bool     `protobuf:"varint,5,opt,name=Valid,proto3" json:"Valid,omitempty"`
	Error                string   `protobuf:"bytes,6,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_29ebabfb014d0758, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *Header) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Header) GetMeta() *any.Any {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Header) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Header) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Witness struct {
	Signatures           []*Signature `protobuf:"bytes,1,rep,name=Signatures,proto3" json:"Signatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Witness) Reset()         { *m = Witness{} }
func (m *Witness) String() string { return proto.CompactTextString(m) }
func (*Witness) ProtoMessage()    {}
func (*Witness) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_29ebabfb014d0758, []int{1}
}
func (m *Witness) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Witness.Unmarshal(m, b)
}
func (m *Witness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Witness.Marshal(b, m, deterministic)
}
func (dst *Witness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Witness.Merge(dst, src)
}
func (m *Witness) XXX_Size() int {
	return xxx_messageInfo_Witness.Size(m)
}
func (m *Witness) XXX_DiscardUnknown() {
	xxx_messageInfo_Witness.DiscardUnknown(m)
}

var xxx_messageInfo_Witness proto.InternalMessageInfo

func (m *Witness) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type Signature struct {
	// Types that are valid to be assigned to Key:
	//	*Signature_PrimaryPublicKey
	//	*Signature_RecoveryPublicKey
	Key                  isSignature_Key `protobuf_oneof:"Key"`
	R                    []byte          `protobuf:"bytes,3,opt,name=R,proto3" json:"R,omitempty"`
	S                    []byte          `protobuf:"bytes,4,opt,name=S,proto3" json:"S,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_29ebabfb014d0758, []int{2}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (dst *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(dst, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

type isSignature_Key interface {
	isSignature_Key()
}

type Signature_PrimaryPublicKey struct {
	PrimaryPublicKey []byte `protobuf:"bytes,1,opt,name=PrimaryPublicKey,proto3,oneof"`
}
type Signature_RecoveryPublicKey struct {
	RecoveryPublicKey []byte `protobuf:"bytes,2,opt,name=RecoveryPublicKey,proto3,oneof"`
}

func (*Signature_PrimaryPublicKey) isSignature_Key()  {}
func (*Signature_RecoveryPublicKey) isSignature_Key() {}

func (m *Signature) GetKey() isSignature_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Signature) GetPrimaryPublicKey() []byte {
	if x, ok := m.GetKey().(*Signature_PrimaryPublicKey); ok {
		return x.PrimaryPublicKey
	}
	return nil
}

func (m *Signature) GetRecoveryPublicKey() []byte {
	if x, ok := m.GetKey().(*Signature_RecoveryPublicKey); ok {
		return x.RecoveryPublicKey
	}
	return nil
}

func (m *Signature) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *Signature) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Signature) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Signature_OneofMarshaler, _Signature_OneofUnmarshaler, _Signature_OneofSizer, []interface{}{
		(*Signature_PrimaryPublicKey)(nil),
		(*Signature_RecoveryPublicKey)(nil),
	}
}

func _Signature_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Signature)
	// Key
	switch x := m.Key.(type) {
	case *Signature_PrimaryPublicKey:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.PrimaryPublicKey)
	case *Signature_RecoveryPublicKey:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.RecoveryPublicKey)
	case nil:
	default:
		return fmt.Errorf("Signature.Key has unexpected type %T", x)
	}
	return nil
}

func _Signature_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Signature)
	switch tag {
	case 1: // Key.PrimaryPublicKey
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Key = &Signature_PrimaryPublicKey{x}
		return true, err
	case 2: // Key.RecoveryPublicKey
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Key = &Signature_RecoveryPublicKey{x}
		return true, err
	default:
		return false, nil
	}
}

func _Signature_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Signature)
	// Key
	switch x := m.Key.(type) {
	case *Signature_PrimaryPublicKey:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.PrimaryPublicKey)))
		n += len(x.PrimaryPublicKey)
	case *Signature_RecoveryPublicKey:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.RecoveryPublicKey)))
		n += len(x.RecoveryPublicKey)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type State struct {
	State                float64              `protobuf:"fixed64,1,opt,name=State,proto3" json:"State,omitempty"`
	PrevState            float64              `protobuf:"fixed64,2,opt,name=PrevState,proto3" json:"PrevState,omitempty"`
	TimeAccepted         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=TimeAccepted,proto3" json:"TimeAccepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_29ebabfb014d0758, []int{3}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetState() float64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *State) GetPrevState() float64 {
	if m != nil {
		return m.PrevState
	}
	return 0
}

func (m *State) GetTimeAccepted() *timestamp.Timestamp {
	if m != nil {
		return m.TimeAccepted
	}
	return nil
}

type Config struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Witness              *Witness `protobuf:"bytes,2,opt,name=Witness,proto3" json:"Witness,omitempty"`
	State                *State   `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"`
	Spec                 *any.Any `protobuf:"bytes,4,opt,name=Spec,proto3" json:"Spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_29ebabfb014d0758, []int{4}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Config) GetWitness() *Witness {
	if m != nil {
		return m.Witness
	}
	return nil
}

func (m *Config) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Config) GetSpec() *any.Any {
	if m != nil {
		return m.Spec
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "v0.Header")
	proto.RegisterType((*Witness)(nil), "v0.Witness")
	proto.RegisterType((*Signature)(nil), "v0.Signature")
	proto.RegisterType((*State)(nil), "v0.State")
	proto.RegisterType((*Config)(nil), "v0.Config")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_config_29ebabfb014d0758) }

var fileDescriptor_config_29ebabfb014d0758 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x9d, 0x34, 0xad, 0xf6, 0x25, 0x82, 0x0e, 0x7b, 0x88, 0x45, 0xdc, 0x12, 0x10, 0x72,
	0xd0, 0x6c, 0x89, 0x17, 0x4f, 0x42, 0x57, 0x84, 0x85, 0x22, 0x94, 0xc9, 0xb2, 0x82, 0xb7, 0x34,
	0x7d, 0x2d, 0x03, 0x6d, 0x26, 0x4c, 0xa6, 0x81, 0xe0, 0x57, 0xf0, 0xe4, 0x07, 0xf0, 0xb3, 0xca,
	0xbc, 0x69, 0x6a, 0xb5, 0xb0, 0xb7, 0x79, 0xff, 0xdf, 0x9f, 0x79, 0xf3, 0xde, 0x7f, 0x20, 0x2c,
	0x55, 0xb5, 0x91, 0xdb, 0xb4, 0xd6, 0xca, 0x28, 0xee, 0xb5, 0xb3, 0xc9, 0xab, 0xad, 0x52, 0xdb,
	0x1d, 0xde, 0x90, 0xb2, 0x3a, 0x6c, 0x6e, 0x8a, 0xaa, 0x73, 0x78, 0x72, 0xfd, 0x3f, 0x32, 0x72,
	0x8f, 0x8d, 0x29, 0xf6, 0xb5, 0x33, 0xc4, 0xbf, 0x18, 0x8c, 0xee, 0xb0, 0x58, 0xa3, 0xe6, 0x6f,
	0x00, 0xe6, 0xb5, 0x7c, 0x40, 0xdd, 0x48, 0x55, 0x45, 0x6c, 0xca, 0x92, 0xb1, 0x38, 0x53, 0x38,
	0x07, 0x7f, 0x21, 0xab, 0x75, 0xe4, 0x11, 0xa1, 0x33, 0x4f, 0xc0, 0xff, 0x8a, 0xa6, 0x88, 0xfc,
	0x29, 0x4b, 0x82, 0xec, 0x2a, 0x75, 0xed, 0xd2, 0xbe, 0x5d, 0x3a, 0xaf, 0x3a, 0x41, 0x0e, 0x7e,
	0x05, 0xc3, 0x87, 0x62, 0x27, 0xd7, 0xd1, 0x70, 0xca, 0x92, 0x67, 0xc2, 0x15, 0x56, 0xfd, 0xa2,
	0xb5, 0xd2, 0xd1, 0x88, 0x2e, 0x75, 0x45, 0xfc, 0x11, 0x9e, 0x7e, 0x93, 0xa6, 0xc2, 0xa6, 0xe1,
	0xef, 0x01, 0x72, 0xb9, 0xad, 0x0a, 0x73, 0xd0, 0xd8, 0x44, 0x6c, 0x3a, 0x48, 0x82, 0xec, 0x79,
	0xda, 0xce, 0xd2, 0x93, 0x2a, 0xce, 0x0c, 0xf1, 0x4f, 0x06, 0xe3, 0x53, 0xc9, 0xdf, 0xc1, 0x8b,
	0xa5, 0x96, 0xfb, 0x42, 0x77, 0xcb, 0xc3, 0x6a, 0x27, 0xcb, 0x05, 0x76, 0x34, 0x57, 0x78, 0xf7,
	0x44, 0x5c, 0x10, 0x9e, 0xc2, 0x4b, 0x81, 0xa5, 0x6a, 0xf1, 0xdc, 0xee, 0x1d, 0xed, 0x97, 0x88,
	0x87, 0xc0, 0x44, 0x34, 0xb0, 0x5c, 0x30, 0x61, 0xab, 0x9c, 0xd6, 0x10, 0x0a, 0x96, 0xdf, 0x0e,
	0x61, 0xb0, 0xc0, 0x2e, 0xfe, 0x01, 0xc3, 0xdc, 0x14, 0x06, 0xed, 0x9c, 0x74, 0xa0, 0xf6, 0x4c,
	0x1c, 0xd5, 0xd7, 0x30, 0x5e, 0x6a, 0x6c, 0x1d, 0xf1, 0x88, 0xfc, 0x15, 0xf8, 0x27, 0x08, 0xef,
	0xe5, 0x1e, 0xe7, 0x65, 0x89, 0xb5, 0xc1, 0x35, 0xb5, 0x0a, 0xb2, 0xc9, 0xc5, 0x8e, 0xef, 0xfb,
	0x48, 0xc5, 0x3f, 0xfe, 0xf8, 0x37, 0x83, 0xd1, 0x67, 0xfa, 0x2b, 0x3c, 0xee, 0x43, 0xa6, 0xfe,
	0x41, 0x06, 0x76, 0x83, 0x4e, 0x11, 0x7d, 0xfc, 0x6f, 0x4f, 0x4b, 0xa7, 0xa7, 0x04, 0x59, 0x60,
	0x4d, 0x47, 0x49, 0x9c, 0x02, 0xb9, 0xee, 0x27, 0x71, 0xcf, 0x19, 0x53, 0x16, 0x56, 0xe8, 0x87,
	0x4a, 0xc0, 0xcf, 0x6b, 0x2c, 0x1f, 0xff, 0x12, 0xd6, 0x71, 0xeb, 0x7f, 0xf7, 0xda, 0xd9, 0x6a,
	0x44, 0xe4, 0xc3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0x14, 0xf6, 0xaf, 0xd8, 0x02, 0x00,
	0x00,
}
