// Code generated by protoc-gen-go. DO NOT EDIT.
// source: disabled.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/lyft/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Disabled struct {
	Reason               string               `protobuf:"bytes,1,opt,name=Reason,proto3" json:"Reason,omitempty"`
	From                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Disabled) Reset()         { *m = Disabled{} }
func (m *Disabled) String() string { return proto.CompactTextString(m) }
func (*Disabled) ProtoMessage()    {}
func (*Disabled) Descriptor() ([]byte, []int) {
	return fileDescriptor_disabled_fe167cf0e7d7576e, []int{0}
}
func (m *Disabled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disabled.Unmarshal(m, b)
}
func (m *Disabled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disabled.Marshal(b, m, deterministic)
}
func (dst *Disabled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disabled.Merge(dst, src)
}
func (m *Disabled) XXX_Size() int {
	return xxx_messageInfo_Disabled.Size(m)
}
func (m *Disabled) XXX_DiscardUnknown() {
	xxx_messageInfo_Disabled.DiscardUnknown(m)
}

var xxx_messageInfo_Disabled proto.InternalMessageInfo

func (m *Disabled) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Disabled) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func init() {
	proto.RegisterType((*Disabled)(nil), "v0.Disabled")
}

func init() { proto.RegisterFile("disabled.proto", fileDescriptor_disabled_fe167cf0e7d7576e) }

var fileDescriptor_disabled_fe167cf0e7d7576e = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xc9, 0x2c, 0x4e,
	0x4c, 0xca, 0x49, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x90, 0x92,
	0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x24, 0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6,
	0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0x14, 0x49, 0x89, 0x97, 0x25, 0xe6, 0x64, 0xa6, 0x24,
	0x96, 0xa4, 0xea, 0xc3, 0x18, 0x10, 0x09, 0xa5, 0x4c, 0x2e, 0x0e, 0x17, 0xa8, 0x79, 0x42, 0x8a,
	0x5c, 0x6c, 0x41, 0xa9, 0x89, 0xc5, 0xf9, 0x79, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x4e, 0x9c,
	0xbb, 0x5e, 0x1e, 0x60, 0x66, 0x29, 0x62, 0x12, 0x60, 0x0c, 0x82, 0x4a, 0x08, 0x59, 0x71, 0xb1,
	0xb8, 0x15, 0xe5, 0xe7, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x1b, 0x49, 0xe9, 0x41, 0xec, 0xd5,
	0x83, 0xd9, 0xab, 0x17, 0x02, 0xb3, 0xd7, 0x89, 0x0b, 0xa4, 0x99, 0x75, 0x13, 0x23, 0x93, 0x10,
	0x43, 0x10, 0x58, 0x8f, 0x13, 0x4b, 0x14, 0x53, 0x99, 0x41, 0x12, 0x1b, 0x58, 0xad, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x53, 0x2c, 0x6c, 0x82, 0xc7, 0x00, 0x00, 0x00,
}
