// Code generated by protoc-gen-go. DO NOT EDIT.
// source: header.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/lyft/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// A Header contains routing and state data on a configuration file.
//
// Both ApiVersion and Kind are used by the router to find the correct handler. Increment
// is used as a protection against replay attacks. This means that for all configuration files, each has
// an increment exactly 1 greater than the last.
//
// example:
//
// header: {
// ApiVersion: "v0Alpha",  // a versioned API
// Kind: "WalletSet",      // WalletSets might be found in multiple ApiVersions as well
// Increment: 14,          // in total 13 other configuration files have been processed before this one.
// }
type Header struct {
	ApiVersion           string   `protobuf:"bytes,1,opt,name=ApiVersion,proto3" json:"ApiVersion,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Increment            int32    `protobuf:"varint,3,opt,name=Increment,proto3" json:"Increment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_header_5149e12ae381f2db, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *Header) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Header) GetIncrement() int32 {
	if m != nil {
		return m.Increment
	}
	return 0
}

func init() {
	proto.RegisterType((*Header)(nil), "v0.Header")
}

func init() { proto.RegisterFile("header.proto", fileDescriptor_header_5149e12ae381f2db) }

var fileDescriptor_header_5149e12ae381f2db = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x48, 0x4d, 0x4c,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x90, 0x12, 0x2f, 0x4b,
	0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0x49, 0xd5, 0x87, 0x31, 0x20, 0x92, 0x4a, 0xf5, 0x5c, 0x6c, 0x1e,
	0x60, 0xc5, 0x42, 0xba, 0x5c, 0x5c, 0x8e, 0x05, 0x99, 0x61, 0xa9, 0x45, 0xc5, 0x99, 0xf9, 0x79,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x4e, 0xbc, 0xbb, 0x5e, 0x1e, 0x60, 0xe6, 0x28, 0x62, 0x13,
	0x60, 0x32, 0x62, 0x8a, 0x2b, 0x0b, 0x42, 0x52, 0x20, 0x24, 0xcb, 0xc5, 0xe2, 0x9d, 0x99, 0x97,
	0x22, 0xc1, 0x04, 0x56, 0xc8, 0x09, 0x52, 0xc8, 0x52, 0xc4, 0x24, 0xc0, 0x18, 0x04, 0x16, 0x16,
	0x52, 0xe7, 0xe2, 0xf4, 0xcc, 0x4b, 0x2e, 0x4a, 0xcd, 0x4d, 0xcd, 0x2b, 0x91, 0x60, 0x56, 0x60,
	0xd4, 0x60, 0x85, 0xaa, 0x91, 0x62, 0x52, 0x60, 0x08, 0x42, 0xc8, 0x39, 0xb1, 0x44, 0x31, 0x95,
	0x19, 0x24, 0xb1, 0x81, 0x5d, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x55, 0x4b, 0x80, 0xaa,
	0xba, 0x00, 0x00, 0x00,
}
