// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identityset.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/lyft/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Identity struct {
	Name     string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Asset    Asset     `protobuf:"varint,2,opt,name=Asset,proto3,enum=v0.Asset" json:"Asset,omitempty"`
	Policies []*Policy `protobuf:"bytes,3,rep,name=Policies,proto3" json:"Policies,omitempty"`
	// Types that are valid to be assigned to State:
	//	*Identity_Enabled
	//	*Identity_Disabled
	State                isIdentity_State `protobuf_oneof:"State"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_identityset_2499749781b8f3cc, []int{0}
}
func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (dst *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(dst, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

type isIdentity_State interface {
	isIdentity_State()
}

type Identity_Enabled struct {
	Enabled *Enabled `protobuf:"bytes,4,opt,name=Enabled,proto3,oneof"`
}
type Identity_Disabled struct {
	Disabled *Disabled `protobuf:"bytes,5,opt,name=Disabled,proto3,oneof"`
}

func (*Identity_Enabled) isIdentity_State()  {}
func (*Identity_Disabled) isIdentity_State() {}

func (m *Identity) GetState() isIdentity_State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Identity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Identity) GetAsset() Asset {
	if m != nil {
		return m.Asset
	}
	return Asset_AssetUnknown
}

func (m *Identity) GetPolicies() []*Policy {
	if m != nil {
		return m.Policies
	}
	return nil
}

func (m *Identity) GetEnabled() *Enabled {
	if x, ok := m.GetState().(*Identity_Enabled); ok {
		return x.Enabled
	}
	return nil
}

func (m *Identity) GetDisabled() *Disabled {
	if x, ok := m.GetState().(*Identity_Disabled); ok {
		return x.Disabled
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Identity) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Identity_OneofMarshaler, _Identity_OneofUnmarshaler, _Identity_OneofSizer, []interface{}{
		(*Identity_Enabled)(nil),
		(*Identity_Disabled)(nil),
	}
}

func _Identity_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Identity)
	// State
	switch x := m.State.(type) {
	case *Identity_Enabled:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Enabled); err != nil {
			return err
		}
	case *Identity_Disabled:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Disabled); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Identity.State has unexpected type %T", x)
	}
	return nil
}

func _Identity_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Identity)
	switch tag {
	case 4: // State.Enabled
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Enabled)
		err := b.DecodeMessage(msg)
		m.State = &Identity_Enabled{msg}
		return true, err
	case 5: // State.Disabled
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Disabled)
		err := b.DecodeMessage(msg)
		m.State = &Identity_Disabled{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Identity_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Identity)
	// State
	switch x := m.State.(type) {
	case *Identity_Enabled:
		s := proto.Size(x.Enabled)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Identity_Disabled:
		s := proto.Size(x.Disabled)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Identity)(nil), "v0.Identity")
}

func init() { proto.RegisterFile("identityset.proto", fileDescriptor_identityset_2499749781b8f3cc) }

var fileDescriptor_identityset_2499749781b8f3cc = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x4d, 0x4a, 0xc4, 0x40,
	0x10, 0x85, 0x53, 0xf9, 0x31, 0x49, 0x25, 0x0e, 0x63, 0x6f, 0x0c, 0x03, 0x42, 0x70, 0x63, 0x10,
	0x8c, 0x21, 0x9e, 0xc0, 0xa0, 0x30, 0x6e, 0x44, 0xda, 0x9d, 0xbb, 0x1e, 0xd3, 0x8b, 0x86, 0x38,
	0x19, 0xa6, 0x9b, 0x40, 0xb6, 0x1e, 0xc1, 0xe3, 0xb8, 0xf2, 0x3a, 0x7a, 0x0a, 0xe9, 0x4e, 0x67,
	0x98, 0x5d, 0xbd, 0xef, 0xbd, 0x47, 0x55, 0xe1, 0x99, 0x68, 0xf9, 0x56, 0x09, 0x35, 0x4a, 0xae,
	0xca, 0xdd, 0xbe, 0x57, 0x3d, 0x71, 0x87, 0x6a, 0x95, 0xee, 0xfa, 0x4e, 0xbc, 0x8f, 0x13, 0x59,
	0xa5, 0x4c, 0x4a, 0xae, 0xa4, 0x55, 0x8b, 0x56, 0x48, 0xb6, 0xe9, 0x78, 0x6b, 0xf5, 0x29, 0xdf,
	0x1e, 0xcb, 0xf3, 0x81, 0x75, 0xa2, 0x65, 0x8a, 0xdf, 0xce, 0xc3, 0x64, 0x5c, 0xfe, 0x01, 0x46,
	0x4f, 0x76, 0x1b, 0xb9, 0x40, 0xff, 0x99, 0x7d, 0xf0, 0x0c, 0x72, 0x28, 0xe2, 0x26, 0xfe, 0xfe,
	0xfd, 0xf1, 0xfc, 0xbd, 0xbb, 0x04, 0x6a, 0x30, 0xb9, 0xc1, 0xe0, 0x5e, 0xef, 0xcc, 0xdc, 0x1c,
	0x8a, 0x45, 0x1d, 0x97, 0x43, 0x55, 0x1a, 0xd0, 0xa4, 0x3a, 0x1a, 0x7e, 0x82, 0xbf, 0x84, 0xdc,
	0xa1, 0x53, 0x8a, 0xd4, 0x18, 0xbd, 0xe8, 0x83, 0x05, 0x97, 0x99, 0x97, 0x7b, 0x45, 0x52, 0xa3,
	0x6e, 0x18, 0x36, 0x36, 0xa8, 0x2b, 0xc1, 0x17, 0xb8, 0x11, 0xd0, 0x43, 0x8e, 0x5c, 0x61, 0xf8,
	0x38, 0x1d, 0x9e, 0xf9, 0x39, 0x14, 0x49, 0x9d, 0xe8, 0x8a, 0x45, 0x6b, 0x87, 0xce, 0x2e, 0xb9,
	0xc6, 0xe8, 0xc1, 0x7e, 0x9c, 0x05, 0x26, 0x99, 0xea, 0xe4, 0xcc, 0xd6, 0x0e, 0x3d, 0xf8, 0x4d,
	0x88, 0xc1, 0xab, 0x62, 0x8a, 0x37, 0xfe, 0x9b, 0x3b, 0x54, 0x9b, 0x13, 0xf3, 0xf9, 0xdd, 0x7f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x96, 0x2b, 0x08, 0x66, 0x01, 0x00, 0x00,
}
