// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Mode int32

const (
	Mode_ModeUnknown Mode = 0
	Mode_Debug       Mode = 1
)

var Mode_name = map[int32]string{
	0: "ModeUnknown",
	1: "Debug",
}
var Mode_value = map[string]int32{
	"ModeUnknown": 0,
	"Debug":       1,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}
func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_info_b4fbdf50f235cb0d, []int{0}
}

type Info struct {
	ApiVersion           string   `protobuf:"bytes,1,opt,name=ApiVersion,proto3" json:"ApiVersion,omitempty"`
	Semantic             string   `protobuf:"bytes,2,opt,name=Semantic,proto3" json:"Semantic,omitempty"`
	Mode                 Mode     `protobuf:"varint,3,opt,name=Mode,proto3,enum=v0.Mode" json:"Mode,omitempty"`
	Kinds                []string `protobuf:"bytes,4,rep,name=Kinds,proto3" json:"Kinds,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_info_b4fbdf50f235cb0d, []int{0}
}
func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (dst *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(dst, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *Info) GetSemantic() string {
	if m != nil {
		return m.Semantic
	}
	return ""
}

func (m *Info) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_ModeUnknown
}

func (m *Info) GetKinds() []string {
	if m != nil {
		return m.Kinds
	}
	return nil
}

func (m *Info) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Info)(nil), "v0.Info")
	proto.RegisterEnum("v0.Mode", Mode_name, Mode_value)
}

func init() { proto.RegisterFile("info.proto", fileDescriptor_info_b4fbdf50f235cb0d) }

var fileDescriptor_info_b4fbdf50f235cb0d = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcc, 0x4b, 0xcb,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x50, 0x9a, 0xc1, 0xc8, 0xc5, 0xe2,
	0x99, 0x97, 0x96, 0x2f, 0x24, 0xc7, 0xc5, 0xe5, 0x58, 0x90, 0x19, 0x96, 0x5a, 0x54, 0x9c, 0x99,
	0x9f, 0x27, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x84, 0x24, 0x22, 0x24, 0xc5, 0xc5, 0x11, 0x9c,
	0x9a, 0x9b, 0x98, 0x57, 0x92, 0x99, 0x2c, 0xc1, 0x04, 0x96, 0x85, 0xf3, 0x85, 0x64, 0xb8, 0x58,
	0x7c, 0xf3, 0x53, 0x52, 0x25, 0x98, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0x38, 0xf4, 0xca, 0x0c, 0xf4,
	0x40, 0xfc, 0x20, 0xb0, 0xa8, 0x90, 0x08, 0x17, 0xab, 0x77, 0x66, 0x5e, 0x4a, 0xb1, 0x04, 0x8b,
	0x02, 0xb3, 0x06, 0x67, 0x10, 0x84, 0x23, 0xa4, 0xc0, 0xc5, 0xed, 0x92, 0x5a, 0x9c, 0x5c, 0x94,
	0x59, 0x50, 0x02, 0xb2, 0x90, 0x15, 0x6c, 0x24, 0xb2, 0x90, 0x96, 0x12, 0xc4, 0x54, 0x21, 0x7e,
	0x2e, 0x6e, 0x10, 0x1d, 0x9a, 0x97, 0x9d, 0x97, 0x5f, 0x9e, 0x27, 0xc0, 0x20, 0xc4, 0xc9, 0xc5,
	0xea, 0x92, 0x9a, 0x54, 0x9a, 0x2e, 0xc0, 0xe8, 0xc4, 0x12, 0xc5, 0x54, 0x66, 0x90, 0xc4, 0x06,
	0xf6, 0x8f, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xe3, 0xa2, 0x12, 0xdd, 0x00, 0x00, 0x00,
}
