// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Mode int32

const (
	Mode_ModeUnknown Mode = 0
	Mode_Debug       Mode = 1
)

var Mode_name = map[int32]string{
	0: "ModeUnknown",
	1: "Debug",
}
var Mode_value = map[string]int32{
	"ModeUnknown": 0,
	"Debug":       1,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}
func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_info_89077d947ac2a691, []int{0}
}

type Info struct {
	ApiVersion           string     `protobuf:"bytes,1,opt,name=ApiVersion,proto3" json:"ApiVersion,omitempty"`
	Semantic             string     `protobuf:"bytes,2,opt,name=Semantic,proto3" json:"Semantic,omitempty"`
	Mode                 Mode       `protobuf:"varint,3,opt,name=Mode,proto3,enum=v0.Mode" json:"Mode,omitempty"`
	Kinds                []string   `protobuf:"bytes,4,rep,name=Kinds,proto3" json:"Kinds,omitempty"`
	Description          string     `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	Sets                 []*any.Any `protobuf:"bytes,6,rep,name=Sets,proto3" json:"Sets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_info_89077d947ac2a691, []int{0}
}
func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (dst *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(dst, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *Info) GetSemantic() string {
	if m != nil {
		return m.Semantic
	}
	return ""
}

func (m *Info) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_ModeUnknown
}

func (m *Info) GetKinds() []string {
	if m != nil {
		return m.Kinds
	}
	return nil
}

func (m *Info) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Info) GetSets() []*any.Any {
	if m != nil {
		return m.Sets
	}
	return nil
}

type ServiceInfo struct {
	ApiVersion           string   `protobuf:"bytes,1,opt,name=ApiVersion,proto3" json:"ApiVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_info_89077d947ac2a691, []int{1}
}
func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (dst *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(dst, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

type RepeatedInfo struct {
	Info                 []*Info  `protobuf:"bytes,1,rep,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepeatedInfo) Reset()         { *m = RepeatedInfo{} }
func (m *RepeatedInfo) String() string { return proto.CompactTextString(m) }
func (*RepeatedInfo) ProtoMessage()    {}
func (*RepeatedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_info_89077d947ac2a691, []int{2}
}
func (m *RepeatedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedInfo.Unmarshal(m, b)
}
func (m *RepeatedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedInfo.Marshal(b, m, deterministic)
}
func (dst *RepeatedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedInfo.Merge(dst, src)
}
func (m *RepeatedInfo) XXX_Size() int {
	return xxx_messageInfo_RepeatedInfo.Size(m)
}
func (m *RepeatedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedInfo proto.InternalMessageInfo

func (m *RepeatedInfo) GetInfo() []*Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*Info)(nil), "v0.Info")
	proto.RegisterType((*ServiceInfo)(nil), "v0.ServiceInfo")
	proto.RegisterType((*RepeatedInfo)(nil), "v0.RepeatedInfo")
	proto.RegisterEnum("v0.Mode", Mode_name, Mode_value)
}

func init() { proto.RegisterFile("info.proto", fileDescriptor_info_89077d947ac2a691) }

var fileDescriptor_info_89077d947ac2a691 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0xdd, 0x7c, 0x94, 0x66, 0x22, 0x5a, 0x96, 0x1e, 0xd6, 0x52, 0x24, 0xe4, 0x14, 0x44,
	0xb7, 0xa1, 0x3e, 0x41, 0xa5, 0x17, 0x11, 0x2f, 0x1b, 0xf4, 0xe0, 0x2d, 0x1f, 0x93, 0xb0, 0xa8,
	0xbb, 0x21, 0x49, 0x23, 0x7d, 0x3d, 0x9f, 0x4c, 0xb2, 0x8b, 0xd2, 0xa3, 0xa7, 0xe5, 0xff, 0x9b,
	0x61, 0x67, 0x7e, 0x03, 0x20, 0x55, 0xad, 0x79, 0xdb, 0xe9, 0x41, 0x53, 0x67, 0x4c, 0x57, 0x57,
	0x8d, 0xd6, 0xcd, 0x07, 0x6e, 0x0c, 0x29, 0x0e, 0xf5, 0x26, 0x57, 0x47, 0x5b, 0x8e, 0xbf, 0x09,
	0x78, 0x8f, 0xaa, 0xd6, 0xf4, 0x1a, 0x60, 0xd7, 0xca, 0x57, 0xec, 0x7a, 0xa9, 0x15, 0x23, 0x11,
	0x49, 0x02, 0x71, 0x42, 0xe8, 0x0a, 0xe6, 0x19, 0x7e, 0xe6, 0x6a, 0x90, 0x25, 0x73, 0x4c, 0xf5,
	0x2f, 0xd3, 0x35, 0x78, 0xcf, 0xba, 0x42, 0xe6, 0x46, 0x24, 0xb9, 0xd8, 0xce, 0xf9, 0x98, 0xf2,
	0x29, 0x0b, 0x43, 0xe9, 0x12, 0xfc, 0x27, 0xa9, 0xaa, 0x9e, 0x79, 0x91, 0x9b, 0x04, 0xc2, 0x06,
	0x1a, 0x41, 0xb8, 0xc7, 0xbe, 0xec, 0x64, 0x3b, 0x4c, 0x03, 0x7d, 0xf3, 0xe5, 0x29, 0xa2, 0x09,
	0x78, 0x19, 0x0e, 0x3d, 0x9b, 0x45, 0x6e, 0x12, 0x6e, 0x97, 0xdc, 0x4a, 0xf0, 0x5f, 0x09, 0xbe,
	0x53, 0x47, 0x61, 0x3a, 0xe2, 0x3b, 0x08, 0x33, 0xec, 0x46, 0x59, 0xe2, 0x7f, 0x54, 0xe2, 0x5b,
	0x38, 0x17, 0xd8, 0x62, 0x3e, 0x60, 0x65, 0xfa, 0xd7, 0xf6, 0x04, 0x8c, 0x98, 0x41, 0x66, 0xfd,
	0x29, 0x0b, 0x43, 0x6f, 0x62, 0x2b, 0x47, 0x2f, 0x21, 0x9c, 0xde, 0x17, 0xf5, 0xae, 0xf4, 0x97,
	0x5a, 0x9c, 0xd1, 0x00, 0xfc, 0x3d, 0x16, 0x87, 0x66, 0x41, 0x1e, 0xbc, 0x37, 0x67, 0x4c, 0x8b,
	0x99, 0x59, 0xed, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x26, 0xe7, 0x60, 0xc7, 0x7f, 0x01, 0x00,
	0x00,
}
