// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: info.proto

package v0

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on Info with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Info) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ApiVersion

	// no validation rules for Semantic

	// no validation rules for Mode

	// no validation rules for Description

	for idx, item := range m.GetSets() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return InfoValidationError{
					field:  fmt.Sprintf("Sets[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// InfoValidationError is the validation error returned by Info.Validate if the
// designated constraints aren't met.
type InfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InfoValidationError) ErrorName() string { return "InfoValidationError" }

// Error satisfies the builtin error interface
func (e InfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InfoValidationError{}

// Validate checks the field values on ServiceInfo with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ServiceInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ApiVersion

	return nil
}

// ServiceInfoValidationError is the validation error returned by
// ServiceInfo.Validate if the designated constraints aren't met.
type ServiceInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServiceInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServiceInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServiceInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServiceInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServiceInfoValidationError) ErrorName() string { return "ServiceInfoValidationError" }

// Error satisfies the builtin error interface
func (e ServiceInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServiceInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServiceInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServiceInfoValidationError{}

// Validate checks the field values on RepeatedInfo with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *RepeatedInfo) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetInfo() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RepeatedInfoValidationError{
					field:  fmt.Sprintf("Info[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// RepeatedInfoValidationError is the validation error returned by
// RepeatedInfo.Validate if the designated constraints aren't met.
type RepeatedInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RepeatedInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RepeatedInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RepeatedInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RepeatedInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RepeatedInfoValidationError) ErrorName() string { return "RepeatedInfoValidationError" }

// Error satisfies the builtin error interface
func (e RepeatedInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRepeatedInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RepeatedInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RepeatedInfoValidationError{}
