// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ownerset.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/lyft/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// OwnerSets define the root owners of a node. The first config file sent to a fresh node must be the OwnerSet, which is
// used as a fail safe and required for further configurations.
//
// Quorum defines the minimum amount of weight needed to perform a root operation. (Each user has a weight attribute)
//
//
type OwnerSet struct {
	Quorum               int32    `protobuf:"varint,1,opt,name=Quorum,proto3" json:"Quorum,omitempty"`
	Owners               []*User  `protobuf:"bytes,2,rep,name=Owners,proto3" json:"Owners,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnerSet) Reset()         { *m = OwnerSet{} }
func (m *OwnerSet) String() string { return proto.CompactTextString(m) }
func (*OwnerSet) ProtoMessage()    {}
func (*OwnerSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ownerset_7bd3dbaa81aef882, []int{0}
}
func (m *OwnerSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerSet.Unmarshal(m, b)
}
func (m *OwnerSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerSet.Marshal(b, m, deterministic)
}
func (dst *OwnerSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerSet.Merge(dst, src)
}
func (m *OwnerSet) XXX_Size() int {
	return xxx_messageInfo_OwnerSet.Size(m)
}
func (m *OwnerSet) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerSet.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerSet proto.InternalMessageInfo

func (m *OwnerSet) GetQuorum() int32 {
	if m != nil {
		return m.Quorum
	}
	return 0
}

func (m *OwnerSet) GetOwners() []*User {
	if m != nil {
		return m.Owners
	}
	return nil
}

func init() {
	proto.RegisterType((*OwnerSet)(nil), "v0.OwnerSet")
}

func init() { proto.RegisterFile("ownerset.proto", fileDescriptor_ownerset_7bd3dbaa81aef882) }

var fileDescriptor_ownerset_7bd3dbaa81aef882 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2f, 0xcf, 0x4b,
	0x2d, 0x2a, 0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x90, 0xe2,
	0x2a, 0x2d, 0x4e, 0x2d, 0x82, 0xf0, 0xa5, 0xc4, 0xcb, 0x12, 0x73, 0x32, 0x53, 0x12, 0x4b, 0x52,
	0xf5, 0x61, 0x0c, 0x88, 0x84, 0x52, 0x34, 0x17, 0x87, 0x3f, 0x48, 0x6b, 0x70, 0x6a, 0x89, 0x90,
	0x22, 0x17, 0x5b, 0x60, 0x69, 0x7e, 0x51, 0x69, 0xae, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xab, 0x13,
	0xe7, 0xae, 0x97, 0x07, 0x98, 0x59, 0xa4, 0x98, 0x14, 0x18, 0x82, 0xa0, 0x12, 0x42, 0x3a, 0x5c,
	0x6c, 0x60, 0xe5, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x1c, 0x7a, 0x65, 0x06, 0x7a,
	0xa1, 0xc5, 0xa9, 0x45, 0x4e, 0x5c, 0x20, 0xc5, 0xac, 0x93, 0x18, 0x99, 0x38, 0x18, 0x83, 0xa0,
	0x6a, 0x9c, 0x58, 0xa2, 0x98, 0xca, 0x0c, 0x92, 0xd8, 0xc0, 0x36, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x57, 0xf3, 0xe8, 0x05, 0xa4, 0x00, 0x00, 0x00,
}
