// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ownerset.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OwnerSet struct {
	Quorum               int32    `protobuf:"varint,1,opt,name=Quorum,proto3" json:"Quorum,omitempty"`
	Owners               []*Owner `protobuf:"bytes,2,rep,name=Owners,proto3" json:"Owners,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnerSet) Reset()         { *m = OwnerSet{} }
func (m *OwnerSet) String() string { return proto.CompactTextString(m) }
func (*OwnerSet) ProtoMessage()    {}
func (*OwnerSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ownerset_b34116029e8538cb, []int{0}
}
func (m *OwnerSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerSet.Unmarshal(m, b)
}
func (m *OwnerSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerSet.Marshal(b, m, deterministic)
}
func (dst *OwnerSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerSet.Merge(dst, src)
}
func (m *OwnerSet) XXX_Size() int {
	return xxx_messageInfo_OwnerSet.Size(m)
}
func (m *OwnerSet) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerSet.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerSet proto.InternalMessageInfo

func (m *OwnerSet) GetQuorum() int32 {
	if m != nil {
		return m.Quorum
	}
	return 0
}

func (m *OwnerSet) GetOwners() []*Owner {
	if m != nil {
		return m.Owners
	}
	return nil
}

type Owner struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	PrimaryPublicKey     string   `protobuf:"bytes,3,opt,name=PrimaryPublicKey,proto3" json:"PrimaryPublicKey,omitempty"`
	RecoveryPublicKey    []string `protobuf:"bytes,4,rep,name=RecoveryPublicKey,proto3" json:"RecoveryPublicKey,omitempty"`
	Weight               int32    `protobuf:"varint,5,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Owner) Reset()         { *m = Owner{} }
func (m *Owner) String() string { return proto.CompactTextString(m) }
func (*Owner) ProtoMessage()    {}
func (*Owner) Descriptor() ([]byte, []int) {
	return fileDescriptor_ownerset_b34116029e8538cb, []int{1}
}
func (m *Owner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Owner.Unmarshal(m, b)
}
func (m *Owner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Owner.Marshal(b, m, deterministic)
}
func (dst *Owner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Owner.Merge(dst, src)
}
func (m *Owner) XXX_Size() int {
	return xxx_messageInfo_Owner.Size(m)
}
func (m *Owner) XXX_DiscardUnknown() {
	xxx_messageInfo_Owner.DiscardUnknown(m)
}

var xxx_messageInfo_Owner proto.InternalMessageInfo

func (m *Owner) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Owner) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Owner) GetPrimaryPublicKey() string {
	if m != nil {
		return m.PrimaryPublicKey
	}
	return ""
}

func (m *Owner) GetRecoveryPublicKey() []string {
	if m != nil {
		return m.RecoveryPublicKey
	}
	return nil
}

func (m *Owner) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*OwnerSet)(nil), "v0.OwnerSet")
	proto.RegisterType((*Owner)(nil), "v0.Owner")
}

func init() { proto.RegisterFile("ownerset.proto", fileDescriptor_ownerset_b34116029e8538cb) }

var fileDescriptor_ownerset_b34116029e8538cb = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2f, 0xcf, 0x4b,
	0x2d, 0x2a, 0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x50, 0x72,
	0xe5, 0xe2, 0xf0, 0x07, 0x89, 0x06, 0xa7, 0x96, 0x08, 0x89, 0x71, 0xb1, 0x05, 0x96, 0xe6, 0x17,
	0x95, 0xe6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x79, 0x42, 0x8a, 0x5c, 0x6c, 0x60,
	0x35, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x9c, 0x7a, 0x65, 0x06, 0x7a, 0x60, 0x91,
	0x20, 0xa8, 0x84, 0xd2, 0x62, 0x46, 0x2e, 0x56, 0x30, 0x53, 0x48, 0x88, 0x8b, 0xc5, 0x2f, 0x31,
	0x37, 0x15, 0x6c, 0x04, 0x67, 0x10, 0x98, 0x2d, 0x24, 0xc2, 0xc5, 0xea, 0x9a, 0x9b, 0x98, 0x99,
	0x23, 0xc1, 0x04, 0x16, 0x84, 0x70, 0x84, 0xb4, 0xb8, 0x04, 0x02, 0x8a, 0x32, 0x73, 0x13, 0x8b,
	0x2a, 0x03, 0x4a, 0x93, 0x72, 0x32, 0x93, 0xbd, 0x53, 0x2b, 0x25, 0x98, 0xc1, 0x0a, 0x30, 0xc4,
	0x85, 0x74, 0xb8, 0x04, 0x83, 0x52, 0x93, 0xf3, 0xcb, 0x52, 0x91, 0x15, 0xb3, 0x28, 0x30, 0x6b,
	0x70, 0x06, 0x61, 0x4a, 0x80, 0x3c, 0x12, 0x9e, 0x9a, 0x99, 0x9e, 0x51, 0x22, 0xc1, 0x0a, 0xf1,
	0x08, 0x84, 0xe7, 0xc4, 0x12, 0xc5, 0x54, 0x66, 0x90, 0xc4, 0x06, 0xf6, 0xbd, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x52, 0x22, 0xf7, 0xab, 0x0f, 0x01, 0x00, 0x00,
}
