// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ownerset.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OwnerSet struct {
	Quorum               int32    `protobuf:"varint,1,opt,name=Quorum,proto3" json:"Quorum,omitempty"`
	Owners               []*User  `protobuf:"bytes,2,rep,name=Owners,proto3" json:"Owners,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnerSet) Reset()         { *m = OwnerSet{} }
func (m *OwnerSet) String() string { return proto.CompactTextString(m) }
func (*OwnerSet) ProtoMessage()    {}
func (*OwnerSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ownerset_f2a50fcc1c71b6a4, []int{0}
}
func (m *OwnerSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerSet.Unmarshal(m, b)
}
func (m *OwnerSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerSet.Marshal(b, m, deterministic)
}
func (dst *OwnerSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerSet.Merge(dst, src)
}
func (m *OwnerSet) XXX_Size() int {
	return xxx_messageInfo_OwnerSet.Size(m)
}
func (m *OwnerSet) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerSet.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerSet proto.InternalMessageInfo

func (m *OwnerSet) GetQuorum() int32 {
	if m != nil {
		return m.Quorum
	}
	return 0
}

func (m *OwnerSet) GetOwners() []*User {
	if m != nil {
		return m.Owners
	}
	return nil
}

func init() {
	proto.RegisterType((*OwnerSet)(nil), "v0.OwnerSet")
}

func init() { proto.RegisterFile("ownerset.proto", fileDescriptor_ownerset_f2a50fcc1c71b6a4) }

var fileDescriptor_ownerset_f2a50fcc1c71b6a4 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2f, 0xcf, 0x4b,
	0x2d, 0x2a, 0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x90, 0xe2,
	0x2a, 0x2d, 0x4e, 0x2d, 0x82, 0xf0, 0x95, 0x5c, 0xb8, 0x38, 0xfc, 0x41, 0x2a, 0x82, 0x53, 0x4b,
	0x84, 0xc4, 0xb8, 0xd8, 0x02, 0x4b, 0xf3, 0x8b, 0x4a, 0x73, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58,
	0x83, 0xa0, 0x3c, 0x21, 0x05, 0x2e, 0x36, 0xb0, 0x9a, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e,
	0x23, 0x0e, 0xbd, 0x32, 0x03, 0xbd, 0xd0, 0xe2, 0xd4, 0xa2, 0x20, 0xa8, 0xb8, 0x13, 0x4b, 0x14,
	0x53, 0x99, 0x41, 0x12, 0x1b, 0xd8, 0x48, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59, 0xd5,
	0x49, 0x87, 0x74, 0x00, 0x00, 0x00,
}
