// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permissions.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Effect int32

const (
	Effect_EffectUnknown Effect = 0
	Effect_Allow         Effect = 1
	Effect_Deny          Effect = 2
)

var Effect_name = map[int32]string{
	0: "EffectUnknown",
	1: "Allow",
	2: "Deny",
}
var Effect_value = map[string]int32{
	"EffectUnknown": 0,
	"Allow":         1,
	"Deny":          2,
}

func (x Effect) String() string {
	return proto.EnumName(Effect_name, int32(x))
}
func (Effect) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_permissions_f52a219b1ff41a5d, []int{0}
}

type Action int32

const (
	Action_ActionUnknown Action = 0
	Action_Alter         Action = 1
	Action_Use           Action = 2
	Action_EnableDisable Action = 3
)

var Action_name = map[int32]string{
	0: "ActionUnknown",
	1: "Alter",
	2: "Use",
	3: "EnableDisable",
}
var Action_value = map[string]int32{
	"ActionUnknown": 0,
	"Alter":         1,
	"Use":           2,
	"EnableDisable": 3,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}
func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_permissions_f52a219b1ff41a5d, []int{1}
}

type ConditionNames int32

const (
	ConditionNames_ConditionNameUnknown ConditionNames = 0
	ConditionNames_AuthLevelGreater     ConditionNames = 1
)

var ConditionNames_name = map[int32]string{
	0: "ConditionNameUnknown",
	1: "AuthLevelGreater",
}
var ConditionNames_value = map[string]int32{
	"ConditionNameUnknown": 0,
	"AuthLevelGreater":     1,
}

func (x ConditionNames) String() string {
	return proto.EnumName(ConditionNames_name, int32(x))
}
func (ConditionNames) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_permissions_f52a219b1ff41a5d, []int{2}
}

type Permission struct {
	Description          string       `protobuf:"bytes,1,opt,name=Description,proto3" json:"Description,omitempty"`
	Effect               Effect       `protobuf:"varint,2,opt,name=Effect,proto3,enum=v0.Effect" json:"Effect,omitempty"`
	Subjects             []string     `protobuf:"bytes,3,rep,name=Subjects,proto3" json:"Subjects,omitempty"`
	Actions              []Action     `protobuf:"varint,4,rep,packed,name=Actions,proto3,enum=v0.Action" json:"Actions,omitempty"`
	Conditions           []*Condition `protobuf:"bytes,5,rep,name=Conditions,proto3" json:"Conditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_permissions_f52a219b1ff41a5d, []int{0}
}
func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (dst *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(dst, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Permission) GetEffect() Effect {
	if m != nil {
		return m.Effect
	}
	return Effect_EffectUnknown
}

func (m *Permission) GetSubjects() []string {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func (m *Permission) GetActions() []Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Permission) GetConditions() []*Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type Condition struct {
	Name                 ConditionNames `protobuf:"varint,1,opt,name=Name,proto3,enum=v0.ConditionNames" json:"Name,omitempty"`
	Args                 *any.Any       `protobuf:"bytes,2,opt,name=Args,proto3" json:"Args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_permissions_f52a219b1ff41a5d, []int{1}
}
func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (dst *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(dst, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetName() ConditionNames {
	if m != nil {
		return m.Name
	}
	return ConditionNames_ConditionNameUnknown
}

func (m *Condition) GetArgs() *any.Any {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*Permission)(nil), "v0.Permission")
	proto.RegisterType((*Condition)(nil), "v0.Condition")
	proto.RegisterEnum("v0.Effect", Effect_name, Effect_value)
	proto.RegisterEnum("v0.Action", Action_name, Action_value)
	proto.RegisterEnum("v0.ConditionNames", ConditionNames_name, ConditionNames_value)
}

func init() { proto.RegisterFile("permissions.proto", fileDescriptor_permissions_f52a219b1ff41a5d) }

var fileDescriptor_permissions_f52a219b1ff41a5d = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xcd, 0x6a, 0xea, 0x40,
	0x14, 0xbe, 0xf9, 0xf1, 0x27, 0x47, 0x94, 0x78, 0x70, 0x91, 0xeb, 0x2a, 0xc8, 0xe5, 0x12, 0x84,
	0x1b, 0x43, 0xee, 0x0b, 0x34, 0xd6, 0xd2, 0x4d, 0x29, 0x65, 0x8a, 0x9b, 0x42, 0x17, 0x49, 0x3a,
	0xda, 0xb4, 0x71, 0x46, 0x32, 0x31, 0xe2, 0xf3, 0xf5, 0xc5, 0x4a, 0x66, 0x9a, 0x54, 0xbb, 0x9a,
	0x39, 0xdf, 0x1f, 0xe7, 0x3b, 0x30, 0xde, 0xd3, 0x62, 0x97, 0x09, 0x91, 0x71, 0x26, 0xfc, 0x7d,
	0xc1, 0x4b, 0x8e, 0x7a, 0x15, 0x4c, 0x7f, 0x6f, 0x39, 0xdf, 0xe6, 0x74, 0x21, 0x91, 0xe4, 0xb0,
	0x59, 0xc4, 0xec, 0xa4, 0xe8, 0xd9, 0x87, 0x06, 0xf0, 0xd0, 0x9a, 0xd0, 0x85, 0xc1, 0x8a, 0x8a,
	0xb4, 0xc8, 0xf6, 0x65, 0xc6, 0x99, 0xa3, 0xb9, 0x9a, 0x67, 0x91, 0x73, 0x08, 0x67, 0xd0, 0xbd,
	0xd9, 0x6c, 0x68, 0x5a, 0x3a, 0xba, 0xab, 0x79, 0xa3, 0x10, 0xfc, 0x2a, 0xf0, 0x15, 0x42, 0xbe,
	0x18, 0x9c, 0x42, 0xff, 0xf1, 0x90, 0xbc, 0xd1, 0xb4, 0x14, 0x8e, 0xe1, 0x1a, 0x9e, 0x45, 0xda,
	0x19, 0xff, 0x40, 0x2f, 0x4a, 0xeb, 0x24, 0xe1, 0x98, 0xae, 0xd1, 0x04, 0x28, 0x88, 0x34, 0x14,
	0xfe, 0x03, 0xb8, 0xe6, 0xec, 0x25, 0x53, 0xc2, 0x8e, 0x6b, 0x78, 0x83, 0x70, 0x58, 0x0b, 0x5b,
	0x94, 0x9c, 0x09, 0x66, 0xcf, 0x60, 0xb5, 0x13, 0xfe, 0x05, 0xf3, 0x3e, 0xde, 0x51, 0xb9, 0xfc,
	0x28, 0xc4, 0x0b, 0x57, 0x4d, 0x08, 0x22, 0x79, 0xf4, 0xc0, 0x8c, 0x8a, 0xad, 0x90, 0x3d, 0x06,
	0xe1, 0xc4, 0x57, 0x47, 0xf2, 0x9b, 0x23, 0xf9, 0x11, 0x3b, 0x11, 0xa9, 0x98, 0x07, 0x4d, 0x67,
	0x1c, 0xc3, 0x50, 0xfd, 0xd6, 0xec, 0x9d, 0xf1, 0x23, 0xb3, 0x7f, 0xa1, 0x05, 0x9d, 0x28, 0xcf,
	0xf9, 0xd1, 0xd6, 0xb0, 0x0f, 0xe6, 0x8a, 0xb2, 0x93, 0xad, 0xcf, 0x97, 0xd0, 0x55, 0x55, 0x6a,
	0x87, 0xfa, 0xfd, 0x70, 0x94, 0xb4, 0xb0, 0x35, 0xec, 0x81, 0xb1, 0x16, 0xd4, 0xd6, 0x65, 0x30,
	0x8b, 0x93, 0x9c, 0xae, 0x32, 0x51, 0x3f, 0xb6, 0x31, 0xbf, 0x82, 0xd1, 0xe5, 0xde, 0xe8, 0xc0,
	0xe4, 0x02, 0xf9, 0x8e, 0x9c, 0x80, 0x1d, 0x1d, 0xca, 0xd7, 0x3b, 0x5a, 0xd1, 0xfc, 0xb6, 0xa0,
	0xb1, 0x4c, 0x5f, 0x9a, 0x4f, 0x7a, 0x15, 0x24, 0x5d, 0xd9, 0xe8, 0xff, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x20, 0x10, 0xc2, 0x10, 0x1d, 0x02, 0x00, 0x00,
}
