// Code generated by protoc-gen-go. DO NOT EDIT.
// source: policy.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import _ "github.com/lyft/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Effect int32

const (
	Effect_EffectUnknown Effect = 0
	Effect_Allow         Effect = 1
	Effect_Deny          Effect = 2
)

var Effect_name = map[int32]string{
	0: "EffectUnknown",
	1: "Allow",
	2: "Deny",
}
var Effect_value = map[string]int32{
	"EffectUnknown": 0,
	"Allow":         1,
	"Deny":          2,
}

func (x Effect) String() string {
	return proto.EnumName(Effect_name, int32(x))
}
func (Effect) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_policy_dce9131a230abcbb, []int{0}
}

type Action int32

const (
	Action_ActionUnknown Action = 0
	Action_Alter         Action = 1
	Action_Use           Action = 2
	Action_EnableDisable Action = 3
)

var Action_name = map[int32]string{
	0: "ActionUnknown",
	1: "Alter",
	2: "Use",
	3: "EnableDisable",
}
var Action_value = map[string]int32{
	"ActionUnknown": 0,
	"Alter":         1,
	"Use":           2,
	"EnableDisable": 3,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}
func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_policy_dce9131a230abcbb, []int{1}
}

type ConditionNames int32

const (
	ConditionNames_ConditionNameUnknown ConditionNames = 0
	ConditionNames_AuthLevelGTE         ConditionNames = 1
	ConditionNames_UsersOwns            ConditionNames = 2
	ConditionNames_InSets               ConditionNames = 3
	ConditionNames_MultiSig             ConditionNames = 4
)

var ConditionNames_name = map[int32]string{
	0: "ConditionNameUnknown",
	1: "AuthLevelGTE",
	2: "UsersOwns",
	3: "InSets",
	4: "MultiSig",
}
var ConditionNames_value = map[string]int32{
	"ConditionNameUnknown": 0,
	"AuthLevelGTE":         1,
	"UsersOwns":            2,
	"InSets":               3,
	"MultiSig":             4,
}

func (x ConditionNames) String() string {
	return proto.EnumName(ConditionNames_name, int32(x))
}
func (ConditionNames) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_policy_dce9131a230abcbb, []int{2}
}

type Policy struct {
	ID                   string       `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Effect               Effect       `protobuf:"varint,3,opt,name=Effect,proto3,enum=v0.Effect" json:"Effect,omitempty"`
	Meta                 []byte       `protobuf:"bytes,4,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Subjects             []string     `protobuf:"bytes,5,rep,name=Subjects,proto3" json:"Subjects,omitempty"`
	Actions              []Action     `protobuf:"varint,6,rep,packed,name=Actions,proto3,enum=v0.Action" json:"Actions,omitempty"`
	Conditions           []*Condition `protobuf:"bytes,7,rep,name=Conditions,proto3" json:"Conditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_dce9131a230abcbb, []int{0}
}
func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (dst *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(dst, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Policy) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Policy) GetEffect() Effect {
	if m != nil {
		return m.Effect
	}
	return Effect_EffectUnknown
}

func (m *Policy) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Policy) GetSubjects() []string {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func (m *Policy) GetActions() []Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Policy) GetConditions() []*Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type Condition struct {
	Name                 ConditionNames `protobuf:"varint,1,opt,name=Name,proto3,enum=v0.ConditionNames" json:"Name,omitempty"`
	Args                 *any.Any       `protobuf:"bytes,2,opt,name=Args,proto3" json:"Args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_dce9131a230abcbb, []int{1}
}
func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (dst *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(dst, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetName() ConditionNames {
	if m != nil {
		return m.Name
	}
	return ConditionNames_ConditionNameUnknown
}

func (m *Condition) GetArgs() *any.Any {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*Policy)(nil), "v0.Policy")
	proto.RegisterType((*Condition)(nil), "v0.Condition")
	proto.RegisterEnum("v0.Effect", Effect_name, Effect_value)
	proto.RegisterEnum("v0.Action", Action_name, Action_value)
	proto.RegisterEnum("v0.ConditionNames", ConditionNames_name, ConditionNames_value)
}

func init() { proto.RegisterFile("policy.proto", fileDescriptor_policy_dce9131a230abcbb) }

var fileDescriptor_policy_dce9131a230abcbb = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xcd, 0x8e, 0xd3, 0x3c,
	0x14, 0xfd, 0xec, 0x64, 0xd2, 0xe6, 0xf6, 0x47, 0xfe, 0xae, 0x46, 0x22, 0xd3, 0x55, 0x54, 0x21,
	0x14, 0x15, 0x91, 0x56, 0xe5, 0x09, 0x52, 0x32, 0x42, 0x95, 0x18, 0x40, 0x29, 0xdd, 0x20, 0xb1,
	0x48, 0x33, 0x6e, 0x09, 0x04, 0xbb, 0x8a, 0xdd, 0x54, 0x7d, 0x35, 0x56, 0xbc, 0x0e, 0x8f, 0xc0,
	0x0e, 0xc5, 0x99, 0x94, 0xe9, 0xac, 0x7c, 0xee, 0x39, 0xe7, 0x1e, 0xf9, 0x1e, 0xe8, 0xef, 0x65,
	0x91, 0x67, 0xa7, 0x70, 0x5f, 0x4a, 0x2d, 0x91, 0x56, 0xb3, 0xd1, 0xcd, 0x4e, 0xca, 0x5d, 0xc1,
	0xa7, 0x86, 0xd9, 0x1c, 0xb6, 0xd3, 0x54, 0x3c, 0xc8, 0xa3, 0x67, 0x55, 0x5a, 0xe4, 0xf7, 0xa9,
	0xe6, 0xd3, 0x16, 0x34, 0xc2, 0xf8, 0x0f, 0x01, 0xe7, 0xa3, 0x09, 0xc2, 0x1b, 0xa0, 0xcb, 0xd8,
	0x23, 0x3e, 0x09, 0xdc, 0x85, 0xfb, 0xf3, 0xf7, 0x2f, 0xcb, 0x2e, 0x29, 0x23, 0x09, 0x5d, 0xc6,
	0xf8, 0x12, 0x7a, 0x31, 0x57, 0x59, 0x99, 0xef, 0x75, 0x2e, 0x85, 0x47, 0x9f, 0x7a, 0x1e, 0xab,
	0x38, 0x06, 0xe7, 0x76, 0xbb, 0xe5, 0x99, 0xf6, 0x2c, 0x9f, 0x04, 0xc3, 0x39, 0x84, 0xd5, 0x2c,
	0x6c, 0x98, 0xe4, 0x41, 0x41, 0x04, 0xfb, 0x8e, 0xeb, 0xd4, 0xb3, 0x7d, 0x12, 0xf4, 0x13, 0x83,
	0x71, 0x04, 0xdd, 0xd5, 0x61, 0xf3, 0x8d, 0x67, 0x5a, 0x79, 0x57, 0xbe, 0x15, 0xb8, 0xc9, 0x79,
	0xc6, 0xe7, 0xd0, 0x89, 0xb2, 0x3a, 0x5d, 0x79, 0x8e, 0x6f, 0xb5, 0xa1, 0x0d, 0x95, 0xb4, 0x12,
	0xbe, 0x02, 0x78, 0x23, 0xc5, 0x7d, 0xde, 0x18, 0x3b, 0xbe, 0x15, 0xf4, 0xe6, 0x83, 0xda, 0x78,
	0x66, 0x93, 0x47, 0x86, 0xf1, 0x17, 0x70, 0xcf, 0x13, 0xbe, 0x00, 0xfb, 0x7d, 0xfa, 0x83, 0x9b,
	0xfb, 0x87, 0x73, 0xbc, 0xd8, 0xaa, 0x05, 0x95, 0x18, 0x1d, 0x03, 0xb0, 0xa3, 0x72, 0xa7, 0x4c,
	0x07, 0xbd, 0xf9, 0x75, 0xd8, 0x74, 0x1e, 0xb6, 0x9d, 0x87, 0x91, 0x38, 0x25, 0xc6, 0x31, 0x99,
	0xb5, 0x3d, 0xe0, 0xff, 0x30, 0x68, 0xd0, 0x5a, 0x7c, 0x17, 0xf2, 0x28, 0xd8, 0x7f, 0xe8, 0xc2,
	0x55, 0x54, 0x14, 0xf2, 0xc8, 0x08, 0x76, 0xc1, 0x8e, 0xb9, 0x38, 0x31, 0x3a, 0x59, 0x80, 0xd3,
	0x9c, 0x52, 0x6f, 0x34, 0xe8, 0xc9, 0x86, 0xe6, 0x25, 0x23, 0xd8, 0x01, 0x6b, 0xad, 0x38, 0xa3,
	0x26, 0x58, 0xa4, 0x9b, 0x82, 0xc7, 0xb9, 0xaa, 0x1f, 0x66, 0x4d, 0x38, 0x0c, 0x2f, 0xff, 0x8d,
	0x1e, 0x5c, 0x5f, 0x30, 0xff, 0x22, 0x19, 0xf4, 0xa3, 0x83, 0xfe, 0xfa, 0x8e, 0x57, 0xbc, 0x78,
	0xfb, 0xe9, 0x96, 0x11, 0x1c, 0x80, 0xbb, 0x56, 0xbc, 0x54, 0x1f, 0x8e, 0x42, 0x31, 0x8a, 0x00,
	0xce, 0x52, 0xac, 0xb8, 0x56, 0xcc, 0xc2, 0x3e, 0x74, 0xef, 0x0e, 0x85, 0xce, 0x57, 0xf9, 0x8e,
	0xd9, 0x0b, 0xfb, 0x33, 0xad, 0x66, 0x1b, 0xc7, 0x9c, 0xfd, 0xfa, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x8d, 0x30, 0x3e, 0x6b, 0x8c, 0x02, 0x00, 0x00,
}
