// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Code int32

const (
	Code_CodeUnknown    Code = 0
	Code_OK             Code = 200
	Code_Internal       Code = 500
	Code_NotImplemented Code = 501
	Code_BadRequest     Code = 400
	Code_UnAuthorized   Code = 401
	Code_Forbidded      Code = 403
)

var Code_name = map[int32]string{
	0:   "CodeUnknown",
	200: "OK",
	500: "Internal",
	501: "NotImplemented",
	400: "BadRequest",
	401: "UnAuthorized",
	403: "Forbidded",
}
var Code_value = map[string]int32{
	"CodeUnknown":    0,
	"OK":             200,
	"Internal":       500,
	"NotImplemented": 501,
	"BadRequest":     400,
	"UnAuthorized":   401,
	"Forbidded":      403,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}
func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_response_5b2d698542cd24f1, []int{0}
}

type Response struct {
	Code                 Code     `protobuf:"varint,1,opt,name=Code,proto3,enum=v0.Code" json:"Code,omitempty"`
	MSG                  string   `protobuf:"bytes,2,opt,name=MSG,proto3" json:"MSG,omitempty"`
	Err                  string   `protobuf:"bytes,3,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_5b2d698542cd24f1, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_CodeUnknown
}

func (m *Response) GetMSG() string {
	if m != nil {
		return m.MSG
	}
	return ""
}

func (m *Response) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "v0.Response")
	proto.RegisterEnum("v0.Code", Code_name, Code_value)
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_response_5b2d698542cd24f1) }

var fileDescriptor_response_5b2d698542cd24f1 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x50, 0xf2,
	0xe1, 0xe2, 0x08, 0x82, 0x8a, 0x0a, 0xc9, 0x70, 0xb1, 0x38, 0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x2a,
	0x30, 0x6a, 0xf0, 0x19, 0x71, 0xe8, 0x95, 0x19, 0xe8, 0x81, 0xf8, 0x41, 0x60, 0x51, 0x21, 0x01,
	0x2e, 0x66, 0xdf, 0x60, 0x77, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x13, 0x24, 0xe2,
	0x5a, 0x54, 0x24, 0xc1, 0x0c, 0x11, 0x71, 0x2d, 0x2a, 0xd2, 0xaa, 0x80, 0x98, 0x20, 0xc4, 0xcf,
	0xc5, 0x0d, 0xa2, 0x43, 0xf3, 0xb2, 0xf3, 0xf2, 0xcb, 0xf3, 0x04, 0x18, 0x84, 0xd8, 0xb9, 0x98,
	0xfc, 0xbd, 0x05, 0x4e, 0x30, 0x0a, 0xf1, 0x72, 0x71, 0x78, 0xe6, 0x95, 0xa4, 0x16, 0xe5, 0x25,
	0xe6, 0x08, 0x7c, 0x61, 0x16, 0x12, 0xe6, 0xe2, 0xf3, 0xcb, 0x2f, 0xf1, 0xcc, 0x2d, 0xc8, 0x49,
	0xcd, 0x4d, 0xcd, 0x2b, 0x49, 0x4d, 0x11, 0xf8, 0xca, 0x2c, 0xc4, 0xcf, 0xc5, 0xe5, 0x94, 0x98,
	0x12, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x30, 0x81, 0x59, 0x48, 0x90, 0x8b, 0x27, 0x34,
	0xcf, 0xb1, 0xb4, 0x24, 0x23, 0xbf, 0x28, 0xb3, 0x2a, 0x35, 0x45, 0x60, 0x22, 0xb3, 0x10, 0x1f,
	0x17, 0xa7, 0x5b, 0x7e, 0x51, 0x52, 0x66, 0x4a, 0x4a, 0x6a, 0x8a, 0xc0, 0x64, 0x66, 0x27, 0x96,
	0x28, 0xa6, 0x32, 0x83, 0x24, 0x36, 0xb0, 0xc7, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x55,
	0x74, 0xe7, 0x91, 0xea, 0x00, 0x00, 0x00,
}
