// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: signatures.proto

package v0

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on Witness with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Witness) Validate() error {
	if m == nil {
		return nil
	}

	if len(m.GetSignatures()) < 1 {
		return WitnessValidationError{
			field:  "Signatures",
			reason: "value must contain at least 1 item(s)",
		}
	}

	for idx, item := range m.GetSignatures() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WitnessValidationError{
					field:  fmt.Sprintf("Signatures[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// WitnessValidationError is the validation error returned by Witness.Validate
// if the designated constraints aren't met.
type WitnessValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WitnessValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WitnessValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WitnessValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WitnessValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WitnessValidationError) ErrorName() string { return "WitnessValidationError" }

// Error satisfies the builtin error interface
func (e WitnessValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWitness.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WitnessValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WitnessValidationError{}

// Validate checks the field values on Signature with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Signature) Validate() error {
	if m == nil {
		return nil
	}

	if len(m.GetR()) < 1 {
		return SignatureValidationError{
			field:  "R",
			reason: "value length must be at least 1 bytes",
		}
	}

	if len(m.GetS()) < 1 {
		return SignatureValidationError{
			field:  "S",
			reason: "value length must be at least 1 bytes",
		}
	}

	switch m.Key.(type) {

	case *Signature_PrimaryPublicKey:
		// no validation rules for PrimaryPublicKey

	case *Signature_RecoveryPublicKey:
		// no validation rules for RecoveryPublicKey

	default:
		return SignatureValidationError{
			field:  "Key",
			reason: "value is required",
		}

	}

	return nil
}

// SignatureValidationError is the validation error returned by
// Signature.Validate if the designated constraints aren't met.
type SignatureValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SignatureValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SignatureValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SignatureValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SignatureValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SignatureValidationError) ErrorName() string { return "SignatureValidationError" }

// Error satisfies the builtin error interface
func (e SignatureValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSignature.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SignatureValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SignatureValidationError{}
