// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/lyft/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction struct {
	Asset       Asset    `protobuf:"varint,1,opt,name=Asset,proto3,enum=v0.Asset" json:"Asset,omitempty"`
	Amount      float64  `protobuf:"fixed64,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Identity    string   `protobuf:"bytes,3,opt,name=Identity,proto3" json:"Identity,omitempty"`
	RecipientID string   `protobuf:"bytes,4,opt,name=RecipientID,proto3" json:"RecipientID,omitempty"`
	Witness     *Witness `protobuf:"bytes,5,opt,name=Witness,proto3" json:"Witness,omitempty"`
	// return values
	Payload              []byte               `protobuf:"bytes,6,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Response             *Response            `protobuf:"bytes,7,opt,name=Response,proto3" json:"Response,omitempty"`
	ReturnedAt           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=ReturnedAt,proto3" json:"ReturnedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_f321c99cf5e32fe0, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetAsset() Asset {
	if m != nil {
		return m.Asset
	}
	return Asset_AssetUnknown
}

func (m *Transaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Transaction) GetRecipientID() string {
	if m != nil {
		return m.RecipientID
	}
	return ""
}

func (m *Transaction) GetWitness() *Witness {
	if m != nil {
		return m.Witness
	}
	return nil
}

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Transaction) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Transaction) GetReturnedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ReturnedAt
	}
	return nil
}

type Transaction_Meta struct {
	Created              *timestamp.Timestamp `protobuf:"bytes,1,opt,name=Created,proto3" json:"Created,omitempty"`
	RecvWindow           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=RecvWindow,proto3" json:"RecvWindow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction_Meta) Reset()         { *m = Transaction_Meta{} }
func (m *Transaction_Meta) String() string { return proto.CompactTextString(m) }
func (*Transaction_Meta) ProtoMessage()    {}
func (*Transaction_Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_f321c99cf5e32fe0, []int{0, 0}
}
func (m *Transaction_Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_Meta.Unmarshal(m, b)
}
func (m *Transaction_Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_Meta.Marshal(b, m, deterministic)
}
func (dst *Transaction_Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_Meta.Merge(dst, src)
}
func (m *Transaction_Meta) XXX_Size() int {
	return xxx_messageInfo_Transaction_Meta.Size(m)
}
func (m *Transaction_Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_Meta proto.InternalMessageInfo

func (m *Transaction_Meta) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Transaction_Meta) GetRecvWindow() *timestamp.Timestamp {
	if m != nil {
		return m.RecvWindow
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "v0.Transaction")
	proto.RegisterType((*Transaction_Meta)(nil), "v0.Transaction.Meta")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_transaction_f321c99cf5e32fe0) }

var fileDescriptor_transaction_f321c99cf5e32fe0 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0xeb, 0x34, 0x6d, 0x1a, 0x27, 0x1a, 0x05, 0x6f, 0xb0, 0xb2, 0x21, 0x80, 0x90, 0x22,
	0x21, 0xd2, 0x32, 0xcc, 0x8a, 0x5d, 0x03, 0x9b, 0x59, 0x20, 0x21, 0x6b, 0xa4, 0x91, 0xd8, 0x79,
	0x9a, 0x4b, 0x65, 0xa9, 0xb5, 0xa3, 0xf8, 0x26, 0x30, 0x2c, 0x59, 0xf2, 0x48, 0xac, 0x78, 0x1d,
	0x5e, 0x02, 0xa1, 0xfc, 0xb8, 0x54, 0x2c, 0x20, 0xab, 0xf8, 0x9c, 0xef, 0x1e, 0x5f, 0xf9, 0xd0,
	0x07, 0xd8, 0x48, 0x6d, 0xe5, 0x0e, 0x95, 0xd1, 0x45, 0xdd, 0x18, 0x34, 0xcc, 0xeb, 0x36, 0xe9,
	0xa3, 0xbd, 0x31, 0xfb, 0x03, 0xac, 0x07, 0xe5, 0xae, 0xfd, 0xb8, 0x46, 0x75, 0x04, 0x8b, 0xf2,
	0x58, 0x8f, 0x50, 0x1a, 0x4b, 0x6b, 0x01, 0xed, 0x74, 0x4a, 0xac, 0xda, 0x6b, 0x89, 0x6d, 0x03,
	0x4e, 0xb9, 0x68, 0xc0, 0xd6, 0x46, 0x5b, 0x98, 0xce, 0x0f, 0x3b, 0x79, 0x50, 0x95, 0x44, 0x58,
	0xbb, 0x9f, 0xd1, 0x78, 0xf2, 0x6b, 0x4e, 0xa3, 0x9b, 0x3f, 0x3b, 0xb0, 0x17, 0x74, 0xb1, 0xed,
	0xa3, 0x39, 0xc9, 0x48, 0x7e, 0x71, 0x19, 0x16, 0xdd, 0xa6, 0x18, 0x84, 0x32, 0xfe, 0xfe, 0xf3,
	0xc7, 0x3c, 0xf8, 0x4a, 0xfc, 0x84, 0x64, 0x33, 0x31, 0x52, 0x2c, 0xa7, 0xcb, 0xed, 0xd1, 0xb4,
	0x1a, 0xb9, 0x97, 0x91, 0x9c, 0x94, 0x49, 0x0f, 0x45, 0x2c, 0x7c, 0x3c, 0x9b, 0x3e, 0x31, 0xf9,
	0xec, 0x19, 0x5d, 0x5d, 0x57, 0xa0, 0x51, 0xe1, 0x3d, 0x9f, 0x67, 0x24, 0x0f, 0xcb, 0xb0, 0x67,
	0xfd, 0xc6, 0x4b, 0x88, 0x38, 0x59, 0xec, 0x39, 0x8d, 0x04, 0xec, 0x54, 0xad, 0x40, 0xe3, 0xf5,
	0x5b, 0xee, 0xff, 0x4d, 0x9e, 0xbb, 0xec, 0x25, 0x0d, 0x6e, 0x15, 0x6a, 0xb0, 0x96, 0x2f, 0x32,
	0x92, 0x47, 0x97, 0x51, 0xbf, 0xee, 0x24, 0x95, 0xb4, 0x9f, 0x5a, 0x7c, 0x23, 0xfd, 0x98, 0xe3,
	0xd8, 0x53, 0x1a, 0xbc, 0x97, 0xf7, 0x07, 0x23, 0x2b, 0xbe, 0xcc, 0x48, 0x1e, 0x4f, 0xd9, 0x5f,
	0x3c, 0x3e, 0x13, 0xce, 0x61, 0x57, 0x74, 0x25, 0xa6, 0xf7, 0xe3, 0xc1, 0x10, 0x1c, 0xf7, 0xc1,
	0x4e, 0x3b, 0x4b, 0x9e, 0x89, 0x13, 0xc9, 0x5e, 0x53, 0x2a, 0x00, 0xdb, 0x46, 0x43, 0xb5, 0x45,
	0xbe, 0x1a, 0xe6, 0xd2, 0x62, 0x6c, 0xb2, 0x70, 0x4d, 0x16, 0x37, 0xae, 0x49, 0x71, 0x46, 0xa7,
	0x9f, 0xa9, 0xff, 0x0e, 0x50, 0xb2, 0x2b, 0x1a, 0xbc, 0x69, 0x40, 0x22, 0x54, 0x43, 0x01, 0xff,
	0x0e, 0x70, 0xe8, 0x78, 0xf3, 0xae, 0xbb, 0x55, 0xba, 0x32, 0x9f, 0x86, 0x26, 0xfe, 0x7b, 0xb3,
	0xa3, 0x4b, 0xff, 0x83, 0xd7, 0x6d, 0xee, 0x96, 0x03, 0xf5, 0xea, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa5, 0x95, 0x8a, 0xc1, 0x90, 0x02, 0x00, 0x00,
}
