// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: transaction.proto

package v0

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on Transaction with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *Transaction) Validate() error {
	if m == nil {
		return nil
	}

	if _, ok := _Transaction_Asset_NotInLookup[m.GetAsset()]; ok {
		return TransactionValidationError{
			field:  "Asset",
			reason: "value must not be in list [0]",
		}
	}

	if _, ok := Asset_name[int32(m.GetAsset())]; !ok {
		return TransactionValidationError{
			field:  "Asset",
			reason: "value must be one of the defined enum values",
		}
	}

	if m.GetAmount() <= 0 {
		return TransactionValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
	}

	if utf8.RuneCountInString(m.GetIdentity()) < 1 {
		return TransactionValidationError{
			field:  "Identity",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetRecipientID()) < 1 {
		return TransactionValidationError{
			field:  "RecipientID",
			reason: "value length must be at least 1 runes",
		}
	}

	if m.GetWitness() == nil {
		return TransactionValidationError{
			field:  "Witness",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetWitness()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransactionValidationError{
				field:  "Witness",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(m.GetPayload()) > 0 {
		return TransactionValidationError{
			field:  "Payload",
			reason: "value length must be at most 0 bytes",
		}
	}

	if v, ok := interface{}(m.GetResponse()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransactionValidationError{
				field:  "Response",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetReturnedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransactionValidationError{
				field:  "ReturnedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// TransactionValidationError is the validation error returned by
// Transaction.Validate if the designated constraints aren't met.
type TransactionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransactionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransactionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransactionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransactionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransactionValidationError) ErrorName() string { return "TransactionValidationError" }

// Error satisfies the builtin error interface
func (e TransactionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransaction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransactionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransactionValidationError{}

var _Transaction_Asset_NotInLookup = map[Asset]struct{}{
	0: {},
}

// Validate checks the field values on Transaction_Meta with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *Transaction_Meta) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetCreated()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Transaction_MetaValidationError{
				field:  "Created",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetRecvWindow()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Transaction_MetaValidationError{
				field:  "RecvWindow",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// Transaction_MetaValidationError is the validation error returned by
// Transaction_Meta.Validate if the designated constraints aren't met.
type Transaction_MetaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Transaction_MetaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Transaction_MetaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Transaction_MetaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Transaction_MetaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Transaction_MetaValidationError) ErrorName() string { return "Transaction_MetaValidationError" }

// Error satisfies the builtin error interface
func (e Transaction_MetaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransaction_Meta.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Transaction_MetaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Transaction_MetaValidationError{}
