// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userset.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/lyft/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserSet struct {
	Set                  string   `protobuf:"bytes,1,opt,name=Set,proto3" json:"Set,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSet) Reset()         { *m = UserSet{} }
func (m *UserSet) String() string { return proto.CompactTextString(m) }
func (*UserSet) ProtoMessage()    {}
func (*UserSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_userset_f0ad0d76898e8a9b, []int{0}
}
func (m *UserSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSet.Unmarshal(m, b)
}
func (m *UserSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSet.Marshal(b, m, deterministic)
}
func (dst *UserSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSet.Merge(dst, src)
}
func (m *UserSet) XXX_Size() int {
	return xxx_messageInfo_UserSet.Size(m)
}
func (m *UserSet) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSet.DiscardUnknown(m)
}

var xxx_messageInfo_UserSet proto.InternalMessageInfo

func (m *UserSet) GetSet() string {
	if m != nil {
		return m.Set
	}
	return ""
}

func (m *UserSet) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*UserSet)(nil), "v0.UserSet")
}

func init() { proto.RegisterFile("userset.proto", fileDescriptor_userset_f0ad0d76898e8a9b) }

var fileDescriptor_userset_f0ad0d76898e8a9b = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2d, 0x4e, 0x2d,
	0x2a, 0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x90, 0xe2, 0x02,
	0x09, 0x41, 0xf8, 0x52, 0xe2, 0x65, 0x89, 0x39, 0x99, 0x29, 0x89, 0x25, 0xa9, 0xfa, 0x30, 0x06,
	0x44, 0x42, 0x29, 0x88, 0x8b, 0x3d, 0xb4, 0x38, 0xb5, 0x28, 0x38, 0xb5, 0x44, 0x48, 0x9a, 0x8b,
	0x39, 0x38, 0xb5, 0x44, 0x82, 0x51, 0x81, 0x51, 0x83, 0xd3, 0x89, 0x73, 0xd7, 0xcb, 0x03, 0xcc,
	0x2c, 0x45, 0x4c, 0x02, 0x8c, 0x41, 0x20, 0x51, 0x21, 0x2d, 0x2e, 0x56, 0x90, 0xba, 0x62, 0x09,
	0x26, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x0e, 0xbd, 0x32, 0x03, 0x3d, 0x90, 0x80, 0x13, 0x17, 0x48,
	0x21, 0xeb, 0x24, 0x46, 0x26, 0x0e, 0xc6, 0x20, 0x88, 0x12, 0x27, 0x96, 0x28, 0xa6, 0x32, 0x83,
	0x24, 0x36, 0xb0, 0x05, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x27, 0xb7, 0xad, 0x9a,
	0x00, 0x00, 0x00,
}
