// Code generated by protoc-gen-go. DO NOT EDIT.
// source: walletset.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/lyft/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Wallet struct {
	Name   string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Asset  Asset             `protobuf:"varint,2,opt,name=Asset,proto3,enum=v0.Asset" json:"Asset,omitempty"`
	Access []*AccessProtocol `protobuf:"bytes,3,rep,name=Access,proto3" json:"Access,omitempty"`
	// Types that are valid to be assigned to State:
	//	*Wallet_Enabled
	//	*Wallet_Disabled
	State                isWallet_State `protobuf_oneof:"State"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Wallet) Reset()         { *m = Wallet{} }
func (m *Wallet) String() string { return proto.CompactTextString(m) }
func (*Wallet) ProtoMessage()    {}
func (*Wallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletset_719c940f2712e782, []int{0}
}
func (m *Wallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wallet.Unmarshal(m, b)
}
func (m *Wallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wallet.Marshal(b, m, deterministic)
}
func (dst *Wallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wallet.Merge(dst, src)
}
func (m *Wallet) XXX_Size() int {
	return xxx_messageInfo_Wallet.Size(m)
}
func (m *Wallet) XXX_DiscardUnknown() {
	xxx_messageInfo_Wallet.DiscardUnknown(m)
}

var xxx_messageInfo_Wallet proto.InternalMessageInfo

type isWallet_State interface {
	isWallet_State()
}

type Wallet_Enabled struct {
	Enabled *Enabled `protobuf:"bytes,4,opt,name=Enabled,proto3,oneof"`
}
type Wallet_Disabled struct {
	Disabled *Disabled `protobuf:"bytes,5,opt,name=Disabled,proto3,oneof"`
}

func (*Wallet_Enabled) isWallet_State()  {}
func (*Wallet_Disabled) isWallet_State() {}

func (m *Wallet) GetState() isWallet_State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Wallet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Wallet) GetAsset() Asset {
	if m != nil {
		return m.Asset
	}
	return Asset_AssetUnknown
}

func (m *Wallet) GetAccess() []*AccessProtocol {
	if m != nil {
		return m.Access
	}
	return nil
}

func (m *Wallet) GetEnabled() *Enabled {
	if x, ok := m.GetState().(*Wallet_Enabled); ok {
		return x.Enabled
	}
	return nil
}

func (m *Wallet) GetDisabled() *Disabled {
	if x, ok := m.GetState().(*Wallet_Disabled); ok {
		return x.Disabled
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Wallet) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Wallet_OneofMarshaler, _Wallet_OneofUnmarshaler, _Wallet_OneofSizer, []interface{}{
		(*Wallet_Enabled)(nil),
		(*Wallet_Disabled)(nil),
	}
}

func _Wallet_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Wallet)
	// State
	switch x := m.State.(type) {
	case *Wallet_Enabled:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Enabled); err != nil {
			return err
		}
	case *Wallet_Disabled:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Disabled); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Wallet.State has unexpected type %T", x)
	}
	return nil
}

func _Wallet_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Wallet)
	switch tag {
	case 4: // State.Enabled
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Enabled)
		err := b.DecodeMessage(msg)
		m.State = &Wallet_Enabled{msg}
		return true, err
	case 5: // State.Disabled
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Disabled)
		err := b.DecodeMessage(msg)
		m.State = &Wallet_Disabled{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Wallet_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Wallet)
	// State
	switch x := m.State.(type) {
	case *Wallet_Enabled:
		s := proto.Size(x.Enabled)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Wallet_Disabled:
		s := proto.Size(x.Disabled)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Wallet)(nil), "v0.Wallet")
}

func init() { proto.RegisterFile("walletset.proto", fileDescriptor_walletset_719c940f2712e782) }

var fileDescriptor_walletset_719c940f2712e782 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x4a, 0xec, 0x30,
	0x14, 0x86, 0x7b, 0xda, 0xb4, 0x9d, 0xa6, 0xbd, 0x73, 0x87, 0x6c, 0x0c, 0x03, 0x42, 0x70, 0x63,
	0x11, 0xac, 0xa5, 0x82, 0xfb, 0x09, 0x0a, 0xb3, 0x12, 0x89, 0x0b, 0xc1, 0x5d, 0xa6, 0xcd, 0x62,
	0x20, 0x5a, 0x99, 0x84, 0xba, 0xf7, 0x11, 0x7c, 0x1c, 0x57, 0xbe, 0x8e, 0xe0, 0x43, 0x48, 0xd2,
	0x56, 0xdc, 0xe5, 0x7c, 0xff, 0x17, 0xfe, 0x73, 0xf0, 0xff, 0x57, 0xa9, 0xb5, 0xb2, 0x46, 0xd9,
	0xea, 0xe5, 0xd0, 0xdb, 0x9e, 0x84, 0x43, 0xbd, 0x2e, 0x64, 0xdb, 0x2a, 0x63, 0x46, 0xb2, 0x2e,
	0xa4, 0x31, 0xca, 0xce, 0xd3, 0xb2, 0xdb, 0x1b, 0xb9, 0xd3, 0xaa, 0x9b, 0xe6, 0x7f, 0xea, 0xf9,
	0xef, 0x78, 0x34, 0x48, 0xbd, 0xef, 0xa4, 0x55, 0x17, 0xf3, 0x63, 0x0c, 0x4e, 0xbe, 0x01, 0x27,
	0x0f, 0xbe, 0x8b, 0x1c, 0x63, 0x74, 0x2b, 0x9f, 0x14, 0x05, 0x06, 0x65, 0xc6, 0xb3, 0x8f, 0xaf,
	0xcf, 0x08, 0x1d, 0xc2, 0x15, 0x08, 0x8f, 0xc9, 0x39, 0x8e, 0x37, 0xae, 0x91, 0x86, 0x0c, 0xca,
	0x65, 0x93, 0x55, 0x43, 0x5d, 0x79, 0xc0, 0x0b, 0xa7, 0xa6, 0x6f, 0x80, 0x56, 0xc0, 0x02, 0x31,
	0x5a, 0xe4, 0x0a, 0x27, 0x1b, 0xbf, 0x2e, 0x8d, 0x58, 0x54, 0xe6, 0x0d, 0xf1, 0xbe, 0x27, 0x77,
	0xae, 0xb9, 0xed, 0x35, 0xc7, 0xee, 0x63, 0xfc, 0x0e, 0xe1, 0x02, 0xc4, 0x64, 0x93, 0x53, 0x9c,
	0xde, 0x8c, 0xab, 0x53, 0xc4, 0xa0, 0xcc, 0x9b, 0xdc, 0x7d, 0x9c, 0xd0, 0x36, 0x10, 0x73, 0x4a,
	0xce, 0xf0, 0xe2, 0x7a, 0xba, 0x99, 0xc6, 0xde, 0x2c, 0x9c, 0x39, 0xb3, 0x6d, 0x20, 0x7e, 0x73,
	0x9e, 0xe2, 0xf8, 0xde, 0x4a, 0xab, 0x38, 0x7a, 0x0c, 0x87, 0x7a, 0x97, 0xf8, 0xdb, 0x2f, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xe0, 0xcd, 0xac, 0x66, 0x01, 0x00, 0x00,
}
