// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/carapace/core/core (interfaces: PermissionManager)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	sql "database/sql"
	proto "github.com/carapace/core/api/v0/proto"
	gomock "github.com/golang/mock/gomock"
	ladon "github.com/ory/ladon"
	reflect "reflect"
)

// MockPermissionManager is a mock of PermissionManager interface
type MockPermissionManager struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionManagerMockRecorder
}

// MockPermissionManagerMockRecorder is the mock recorder for MockPermissionManager
type MockPermissionManagerMockRecorder struct {
	mock *MockPermissionManager
}

// NewMockPermissionManager creates a new mock instance
func NewMockPermissionManager(ctrl *gomock.Controller) *MockPermissionManager {
	mock := &MockPermissionManager{ctrl: ctrl}
	mock.recorder = &MockPermissionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPermissionManager) EXPECT() *MockPermissionManagerMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockPermissionManager) Add(arg0 context.Context, arg1 *sql.Tx, arg2 *proto.Policy, arg3, arg4 string) error {
	ret := m.ctrl.Call(m, "Add", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add
func (mr *MockPermissionManagerMockRecorder) Add(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockPermissionManager)(nil).Add), arg0, arg1, arg2, arg3, arg4)
}

// All mocks base method
func (m *MockPermissionManager) All(arg0 context.Context, arg1 *sql.Tx) ([]*proto.Policy, error) {
	ret := m.ctrl.Call(m, "All", arg0, arg1)
	ret0, _ := ret[0].([]*proto.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All
func (mr *MockPermissionManagerMockRecorder) All(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockPermissionManager)(nil).All), arg0, arg1)
}

// Delete mocks base method
func (m *MockPermissionManager) Delete(arg0 context.Context, arg1 *sql.Tx, arg2 *proto.Policy) error {
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockPermissionManagerMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPermissionManager)(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method
func (m *MockPermissionManager) Get(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string) ([]*proto.Policy, error) {
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*proto.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockPermissionManagerMockRecorder) Get(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPermissionManager)(nil).Get), arg0, arg1, arg2, arg3)
}

// IsAllowed mocks base method
func (m *MockPermissionManager) IsAllowed(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4 *ladon.Request) error {
	ret := m.ctrl.Call(m, "IsAllowed", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAllowed indicates an expected call of IsAllowed
func (mr *MockPermissionManagerMockRecorder) IsAllowed(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAllowed", reflect.TypeOf((*MockPermissionManager)(nil).IsAllowed), arg0, arg1, arg2, arg3, arg4)
}

// PoliciesAllow mocks base method
func (m *MockPermissionManager) PoliciesAllow(arg0 *ladon.Request, arg1 []*proto.Policy, arg2 string) error {
	ret := m.ctrl.Call(m, "PoliciesAllow", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PoliciesAllow indicates an expected call of PoliciesAllow
func (mr *MockPermissionManagerMockRecorder) PoliciesAllow(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PoliciesAllow", reflect.TypeOf((*MockPermissionManager)(nil).PoliciesAllow), arg0, arg1, arg2)
}

// Set mocks base method
func (m *MockPermissionManager) Set(arg0 context.Context, arg1 *sql.Tx, arg2 []*proto.Policy, arg3, arg4 string) error {
	ret := m.ctrl.Call(m, "Set", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockPermissionManagerMockRecorder) Set(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockPermissionManager)(nil).Set), arg0, arg1, arg2, arg3, arg4)
}
